Repository istio/api, pull requests merged in 2018-10, with the labels that each got.

#642 Fix doc typo
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes

#644 Update weighted cluster support docs in TCP/TLS
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#645 Add fields to allow min/max TLS version and supported cipher suites
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  python/istio_api/networking/v1alpha3/gateway_pb2.py
Labels: cla: yes

#647 Update documentation related to weighted routes
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes

#638 Add option for LightStep tracing to ProxyConfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes

#648 Add sampling parameters to Rule
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  policy/v1beta1/type.pb.go
  python/istio_api/policy/v1beta1/cfg_pb2.py
Labels: approved, cla: yes, lgtm

#654 Fix typo in gateway.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#646 Updates to service entries
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  python/istio_api/networking/v1alpha3/gateway_pb2.py
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
Labels: approved, cla: yes, lgtm

#655 policy: add missing APA attribute bindings
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  python/istio_api/policy/v1beta1/cfg_pb2.py
Labels: approved, cla: yes, lgtm

#657 Cleanup Mesh config
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: approved, cla: yes, lgtm

#658 add flag to meshconfig to indicate whether token volume mount it enabled
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#659 Add timeout to mixer remote handler
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  python/istio_api/policy/v1beta1/cfg_pb2.py
Labels: approved, cla: yes, lgtm

#660 add field to global config for setting the access log format to text or json
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes

#656 Multicluster/partial-registry view network configuration API
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/mesh.pb.go
  mesh/v1alpha1/mesh.proto
  python/istio_api/mesh/v1alpha1/mesh_pb2.py
Labels: approved, cla: yes, lgtm

#664 Updating description of network definitions
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  python/istio_api/mesh/v1alpha1/network_pb2.py
Labels: cla: yes

#666 Added MeshNetworks
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  python/istio_api/mesh/v1alpha1/network_pb2.py
Labels: cla: yes

#667 Cherry picked network config
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/mesh.pb.go
  mesh/v1alpha1/mesh.proto
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  python/istio_api/mesh/v1alpha1/mesh_pb2.py
  python/istio_api/mesh/v1alpha1/network_pb2.py
Labels: cla: no

#671 Update OWNERS to include ozevren
  OWNERS
Labels: approved, cla: yes, lgtm

#672 Add mesh config to allow setting network policy fail open
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes

#676 Cherry pick PRs from master
  OWNERS
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: no, lgtm

#679 Add HTTPRetry config to allow setting retryOn policy
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes

#678 Minor correction to avoid confusion in ServiceEntry reference doc
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
Labels: cla: yes

#681 use lowercase_with_underscore for field name `retry_on`
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#673 Add stdduration annotation to timeout
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  python/istio_api/policy/v1beta1/cfg_pb2.py
Labels: approved, cla: yes, lgtm

#675 Add Protolock.
  .circleci/config.yml
  Makefile
  README.md
  proto.lock
  prow/api-presubmit.sh
  scripts/pre-commit
  tools/all/Dockerfile
  tools/all/build-and-push.sh
  tools/protoc/Dockerfile
  tools/protoc/build-and-push.sh
  tools/protolock/Dockerfile
  tools/protolock/build-and-push.sh
Labels: approved, cla: yes, lgtm

#680 re-add deprecated fields, but hide from docs.
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: approved, lgtm
