Repository istio/api, pull requests merged in 2018-12, with the labels that each got.

#721 Merge release-1.1 into master
  Makefile
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_dependency.pb.go
  networking/v1alpha3/service_dependency.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1alpha3/service_dependency_pb2.py
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#725 Fix typo, 'target' is not known
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
Labels: approved, cla: yes, lgtm, needs-ok-to-test

#729 add enable_sds_k8s_sa_jwt flag to meshconfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#700 Add note to readme about backwards incompatible changes
  README.md
Labels: cla: yes

#606 oop adapter connection auth config
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  proto.lock
  python/istio_api/policy/v1beta1/cfg_pb2.py
Labels: approved, cla: yes, lgtm

#739 Fix a comment.
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes

#740 Fix a comment.
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
Labels: approved, cla: yes

#726 Add per service locality weight setting
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: approved, cla: yes, lgtm
