Repository istio/api, pull requests merged in 2018-11, with the labels that each got.

#685 Add prototool for linting, precommit, Circle, Prow.
  .circleci/config.yml
  Makefile
  prototool.yaml
  prow/api-presubmit.sh
  scripts/pre-commit
  tools/all/Dockerfile
Labels: approved, cla: yes, lgtm

#690 Fix style for TLS enum in networking.
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  python/istio_api/networking/v1alpha3/gateway_pb2.py
Labels: cla: yes

#691 Merge mixer protos
  mixer/v1/attributes.pb.go
  mixer/v1/mixer.pb.go
  mixer/v1/mixer.proto
  mixer/v1/report.pb.go
  mixer/v1/report.proto
  mixer/v1/service.pb.go
  mixer/v1/service.proto
  proto.lock
  prototool.yaml
  python/istio_api/mixer/v1/mixer_pb2.py
  python/istio_api/mixer/v1/report_pb2.py
  python/istio_api/mixer/v1/service_pb2.py
Labels: approved, cla: yes, lgtm

#693 Add TcpClusterRewrite config proto
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.proto
  proto.lock
  python/istio_api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config_pb2.py
Labels: cla: yes

#694 remove references to envoyproxy.io api-v1
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
Labels: approved, cla: yes, lgtm

#698 policy: documentation for route directive
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
Labels: approved, cla: yes, lgtm

#697 add trust domain to meshconfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#496 Add support for healthy panic threshold
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: cla: yes

#699 Merge release-1.1 to master
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1alpha3/gateway_pb2.py
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: no, do-not-merge/hold, lgtm

#704 Adding weights to service entry endpoints
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
Labels: approved, cla: yes

#706 [Cherry-pick]Adding weights to service entry endpoints (#704)
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  proto.lock
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
Labels: approved, cla: yes, lgtm

#705 Merge missing commits from master to release-1.1
  .circleci/config.yml
  Makefile
  README.md
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.proto
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/attributes.pb.go
  mixer/v1/mixer.pb.go
  mixer/v1/mixer.proto
  mixer/v1/report.pb.go
  mixer/v1/report.proto
  mixer/v1/service.pb.go
  mixer/v1/service.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  proto.lock
  prototool.yaml
  prow/api-presubmit.sh
  python/istio_api/envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mixer/v1/mixer_pb2.py
  python/istio_api/mixer/v1/report_pb2.py
  python/istio_api/mixer/v1/service_pb2.py
  python/istio_api/policy/v1beta1/cfg_pb2.py
  scripts/pre-commit
  tools/all/Dockerfile
  tools/all/build-and-push.sh
  tools/protoc/Dockerfile
  tools/protoc/build-and-push.sh
  tools/protolock/Dockerfile
  tools/protolock/build-and-push.sh
Labels: approved, cla: no, lgtm

#702 bazel: Allow to distdir all dependencies
  WORKSPACE
  scripts/check-repositories
  scripts/pre-commit
Labels: approved, cla: yes, lgtm, ok-to-test

#711 fix naming convention between access log format vs encoding
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#712 Revert "fix naming convention between access log format vs encoding"
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#713 add access log encoding
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#710 fix naming convention between access log format vs encoding
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#714 clarify http match example
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, ok-to-test

#718 API changes to enable TCP keepalive configuration.
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: approved, cla: yes, lgtm, ok-to-test

#709 allow setting headers
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm, ok-to-test

#719 NetworkScopes
  Makefile
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/network_scope.pb.go
  networking/v1alpha3/network_scope.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1alpha3/network_scope_pb2.py
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes
