Repository istio/api, pull requests merged in 2018-09, with the labels that each got.

#627 Document sni_hosts must be subset of VS hosts
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes

#631 Remove special case conversion of "Struct" => interface{} for Mixer config protos.
  Makefile
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/fixed_cfg.pb.go
Labels: approved, cla: yes, lgtm

#630 Revert the deprecation of peer_is_optional and origin_is_optional.
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  python/istio_api/authentication/v1alpha1/policy_pb2.py
Labels: approved, cla: yes, lgtm

#629 Change TargetSelector documentation to be 'workload oriented'
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
Labels: approved, cla: yes, lgtm

#625 Cml/removeheaders
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#624 remove deprecated MixerAddress
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes

#634 Document subset without labels
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
Labels: cla: yes

#626 Added headers manipulations capabilities to DestinationWeight
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#635 add arena allocation for mixer client proto
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/check.pb.go
  mixer/v1/check.proto
  mixer/v1/report.pb.go
  mixer/v1/report.proto
  python/istio_api/mixer/v1/attributes_pb2.py
  python/istio_api/mixer/v1/check_pb2.py
  python/istio_api/mixer/v1/report_pb2.py
Labels: cla: yes, lgtm

#637 remove sdsrefreshdelay from meshconfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes

#639 remove out of date fields from config
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes

#640 fix: typo
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
Labels: approved, cla: yes, lgtm

#641 Rename DestinationWeight and cleanup add/remove headers
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm
