Repository istio/api, pull requests merged in 2019-08, with the labels that each got.

#1015 Fix go.mod file.
  go.mod
  go.sum
Labels: cla: yes, size/S

#1017 Add a Galley annotation.
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/S

#1018 Remove mergify link.
  README.md
Labels: cla: yes, size/XS

#1019 Add context.proxy_version into mixer attributes dictionary
  mixer/v1/global_dictionary.yaml
Labels: cla: yes, size/XS

#1021 Fix OpenAPI dependency tracking.
  Makefile.core.mk
Labels: cla: yes, size/M

#1023 [proxy] Add TLS Settings for envoy ALS and metrics services
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, size/L

#1024 Add Keepalive settings for envoy ALS and metrics services
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, ok-to-test, size/S

#1026 Named routes in VS and few more fields in envoyfilter api
  networking/v1alpha3/envoy_filter.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/networking/v1alpha3/envoy_filter_pb2.py
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, size/XL

#918 Add authorization policy v1beta1
  Makefile.core.mk
  cue.yaml
  proto.lock
  python/istio_api/security/v1beta1/authorization_pb2.py
  security/v1beta1/authorization.json
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.pb.html
  security/v1beta1/authorization.proto
Labels: cla: yes, size/XXL

#1025 Switch to the build-tools image
  Makefile.core.mk
Labels: cla: yes, size/XS

#1031 remove the out-dated authorization policy
  proto.lock
  python/istio_api/rbac/v1alpha1/rbac_pb2.py
  rbac/v1alpha1/istio.rbac.v1alpha1.json
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  releaselocks/release-1.1/proto.lock.status
Labels: cla: yes, size/L

#1033 Protocol Detection Timeout
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/L

#1034 Update to latest container image.
  Makefile.core.mk
Labels: cla: yes, size/XS

#1032 Add WorkloadSelector definition in a common directory.
  Makefile.core.mk
  cue.yaml
  proto.lock
  python/istio_api/security/v1beta1/authorization_pb2.py
  python/istio_api/type/v1beta1/selector_pb2.py
  security/v1beta1/authorization.json
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.pb.html
  security/v1beta1/authorization.proto
  type/v1beta1/selector.json
  type/v1beta1/selector.pb.go
  type/v1beta1/selector.pb.html
  type/v1beta1/selector.proto
Labels: cla: yes, size/L

#1035 Set release managers as CODEOWNERS for release-1.3
  CODEOWNERS
Labels: area/test and release, cla: yes, size/XS

#1039 Sidecar doc updates
  networking/v1alpha3/sidecar.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: cla: yes, size/S

#1041 [release-1.3] Sidecar doc updates
  networking/v1alpha3/sidecar.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: cla: no, size/S

#1044 Use the merged build tool image
  Makefile
  Makefile.core.mk
  authentication/v1alpha1/istio.authentication.v1alpha1.json
  mcp/v1alpha1/istio.mcp.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.json
  mixer/v1/config/client/istio.mixer.v1.config.client.json
  mixer/v1/istio.mixer.v1.json
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/envoy_filter.json
  networking/v1alpha3/gateway.json
  networking/v1alpha3/service_entry.json
  networking/v1alpha3/sidecar.json
  networking/v1alpha3/virtual_service.json
  policy/v1beta1/istio.policy.v1beta1.json
  rbac/v1alpha1/istio.rbac.v1alpha1.json
Labels: cla: yes, size/XXL

#1046 Switch this repo to BUILD_WITH_CONTAINER=1
  .commonfiles.sha
  Makefile
  Makefile.common.mk
  Makefile.core.mk
  Makefile.overrides.mk
  README.md
  SUPPORT.md
  prow/api-postsubmit.sh
  prow/api-presubmit.sh
Labels: cla: yes, size/L

#1037 typo fix rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/istio.rbac.v1alpha1.json
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: cla: yes, ok-to-test, size/M

#1048 Update sidecar and gateway hosts doc
  networking/v1alpha3/gateway.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: cherrypick/release-1.3, cla: yes, size/S

#1049 [release-1.3] Update sidecar and gateway hosts doc
  networking/v1alpha3/gateway.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: cla: yes, size/S

#1028 Add feature flag enable_auto_mtls in mesh config.
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/L

#1052 Fix outdated XDS url link
  mcp/Readme.md
Labels: cla: yes, ok-to-test, size/XS

#1063 add stat name patterns to mesh config
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/L

#1066 Update CODEOWNERS
  CODEOWNERS
Labels: cla: yes, size/XS
