Repository istio/api, pull requests merged in 2019-03, with the labels that each got.

#826 Update gateway and sidecar hosts doc
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: approved, cla: yes

#831 Update API docs (service entry, gateway, sidecar)
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: approved, cla: yes

#829 Add jwks to JWT policy to allow using public key for token validation.
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  proto.lock
  python/istio_api/authentication/v1alpha1/policy_pb2.py
Labels: approved, area/security, cla: yes, lgtm

#832 add configurable dns refresh rate to mesh for strict dns cluster,
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes

#836 change gateway to gateways
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
Labels: approved, cla: yes, lgtm, ok-to-test

#833 Hosts are not ignored in ServiceEntry for HTTPs
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
Labels: approved, cla: yes

#846 Stable marshaler for mixer configs
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/api_spec.proto
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/quota.proto
  mixer/v1/config/client/service.pb.go
  mixer/v1/config/client/service.proto
  python/istio_api/mixer/v1/attributes_pb2.py
  python/istio_api/mixer/v1/config/client/api_spec_pb2.py
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
  python/istio_api/mixer/v1/config/client/quota_pb2.py
  python/istio_api/mixer/v1/config/client/service_pb2.py
Labels: approved, cla: yes, lgtm

#830 Update prototool.
  .circleci/config.yml
  Makefile
  proto.lock
  tools/all/Dockerfile
  tools/protolock/Dockerfile
Labels: approved, cla: yes, lgtm

#854 Fix some doc errors.
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  dictionaries/custom.txt
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.proto
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  mixer/v1/config/client/service.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes

#856 Fix two more broken links.
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/istio.mixer.v1.pb.html
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
Labels: approved, cla: yes

#857 Example CRD instances must be valid
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#707 Setup CI to test for incompatible changes against 1.0 and 1.1
  .circleci/config.yml
  Makefile
  prow/api-presubmit.sh
  releaselocks/release-1.0/proto.lock
  releaselocks/release-1.0/proto.lock.status
  releaselocks/release-1.1/proto.lock
  releaselocks/release-1.1/proto.lock.status
  scripts/check-release-locks.md
  scripts/check-release-locks.sh
Labels: approved, cla: yes, lgtm

#849 Fix example Sidecar structure
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: approved, cla: yes, lgtm

#859 .protos should have valid CRDs in comments
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#841 fix MeshNetworks demo
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
Labels: approved, cla: yes, lgtm

#860 Add support for inline role definition
  proto.lock
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#865 last minute doc fixes
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: no, lgtm

#866 Delete obsolete leftover file.
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
Labels: approved, cla: yes, lgtm

#800 Clearify comment for server_name field in Mixer oop auth config
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
Labels: approved, cla: yes

#827 add mixerclient config to istio.io reference docs
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Labels: approved, cla: yes, lgtm

#867 Envoyfilter docs fix
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: cla: yes

#868 Tweaks to get the mixer client config docs to be published.
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Labels: approved, cla: yes

#869 ns of egress gateway should be istio-system in the context
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
Labels: approved, cla: yes, lgtm, ok-to-test

#871 Gateway selector doc correction
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
Labels: approved, cla: yes

#873 update host desc that more than one vs share same host
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#822 Add Datadog tracing to proxy config (release-1.1)
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: approved, cla: yes, ok-to-test

#875 Add recommendation for gateway selector
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
Labels: approved, cla: yes, lgtm

#872 Merge release-1.1 into master
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  dictionaries/custom.txt
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.proto
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/api_spec.proto
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/quota.proto
  mixer/v1/config/client/service.pb.go
  mixer/v1/config/client/service.proto
  mixer/v1/istio.mixer.v1.pb.html
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  python/istio_api/mixer/v1/attributes_pb2.py
  python/istio_api/mixer/v1/config/client/api_spec_pb2.py
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
  python/istio_api/mixer/v1/config/client/quota_pb2.py
  python/istio_api/mixer/v1/config/client/service_pb2.py
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#876 Be precise about 'workload' vs 'workload instance'
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#884 add sds related param to proxyconfig proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: approved, cla: yes, lgtm

#889 Update to latest doc gen tool.
  .circleci/config.yml
  Makefile
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  dictionaries/custom.txt
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  mcp/v1alpha1/istio.mcp.v1alpha1.pb.html
  mcp/v1alpha1/mcp.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  mixer/adapter/model/v1beta1/check.pb.go
  mixer/adapter/model/v1beta1/infrastructure_backend.pb.go
  mixer/adapter/model/v1beta1/quota.pb.go
  mixer/v1/attributes.pb.go
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/quota.pb.go
  mixer/v1/mixer.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/type.pb.go
  rbac/v1alpha1/rbac.pb.go
  tools/all/Dockerfile
Labels: approved, cla: yes

#881 Fix ISTIO_META_USER_SDS styling in docs
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
Labels: cla: yes
