Repository istio/api, pull requests merged in 2019-02, with the labels that each got.

#786 Update comment for credentialName
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
Labels: cla: yes

#788 Doc fixes
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/istio.mixer.v1.pb.html
Labels: approved, cla: yes

#792 Add transport error retry config to mixer client.
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  proto.lock
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
Labels: cla: yes

#791 Rename "principals" to "names".
  proto.lock
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: cla: yes, lgtm

#794 Doc fix to have the mesh config show up on istio.io.
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: approved, cla: yes

#795 Fix typos in sidecar.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
Labels: cla: yes, needs-ok-to-test

#796 Fix typos in sidecar.proto (1.1)
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
Labels: cla: yes, needs-ok-to-test

#789 add server_name to mixer remote handler tls / mtls
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  proto.lock
  python/istio_api/policy/v1beta1/cfg_pb2.py
Labels: approved, cla: yes

#798 Generate files with correct owner
  Makefile
Labels: cla: yes, needs-ok-to-test

#797 Add options for Datadog tracing in proxy config
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: approved, cla: yes, lgtm, ok-to-test

#801 networking doc: typo fixes
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#806 Merge 1.1 to master
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/istio.mixer.v1.pb.html
  mixer/v1/mixer.pb.go
  mixer/v1/mixer.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
  python/istio_api/mixer/v1/mixer_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1alpha3/gateway_pb2.py
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
  python/istio_api/policy/v1beta1/cfg_pb2.py
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, do-not-merge/work-in-progress

#805 Add high-level overview and diagrams for MCP
  mcp/Readme.md
  mcp/v1alpha1/diagrams/ResourceSink-connection-setup.svg
  mcp/v1alpha1/diagrams/ResourceSource-connection-setup.svg
  mcp/v1alpha1/diagrams/collection-full-state-update-success.svg
  mcp/v1alpha1/diagrams/collection-incremental-update-success.svg
  mcp/v1alpha1/diagrams/collection-update-error.svg
Labels: approved, cla: yes, lgtm

#803 Add envoy metrics service configuration to ProxyConfig
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, ok-to-test

#808 Fix api document
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
Labels: approved, cla: yes, lgtm

#809 Rename metrics_service_address to clarify that it is for Envoy's API
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, ok-to-test

#811 Generate separate HTML page per proto under networking
  Makefile
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: no, lgtm

#814 Remove myself from owners add utka instead
  OWNERS
Labels: approved, cla: yes

#810 fix mcp update error diagram
  mcp/v1alpha1/diagrams/collection-update-error.svg
Labels: cla: yes

#815 update istio/tools
  .circleci/config.yml
  Makefile
  authentication/v1alpha1/policy.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.proto
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  mcp/v1alpha1/mcp.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  mixer/adapter/model/v1beta1/check.pb.go
  mixer/adapter/model/v1beta1/extensions.pb.go
  mixer/adapter/model/v1beta1/info.pb.go
  mixer/adapter/model/v1beta1/infrastructure_backend.pb.go
  mixer/adapter/model/v1beta1/quota.pb.go
  mixer/adapter/model/v1beta1/report.pb.go
  mixer/adapter/model/v1beta1/template.pb.go
  mixer/v1/attributes.pb.go
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/service.pb.go
  mixer/v1/mixer.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/http_response.pb.go
  policy/v1beta1/type.pb.go
  policy/v1beta1/value_type.pb.go
  rbac/v1alpha1/rbac.pb.go
Labels: approved, cla: yes, lgtm

#818 repeat: Generate separate HTML page per proto under networking
  Makefile
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/istio.networking.v1alpha3.pb.html
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#817 Minor updates for building docker images.
  tools/all/Dockerfile
  tools/all/build-and-push.sh
  tools/protoc/build-and-push.sh
Labels: approved, cla: yes

#819 Add spell checking for docs.
  Makefile
  dictionaries/custom.txt
  dictionaries/en-US.aff
  dictionaries/en-US.dic
Labels: approved, cla: yes

#820 Document exportTo restrictions
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes

#821 Doc fixes.
  dictionaries/custom.txt
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
  mixer/adapter/model/v1beta1/template.pb.go
  mixer/adapter/model/v1beta1/template.proto
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  policy/v1beta1/type.pb.go
  policy/v1beta1/type.proto
Labels: approved, cla: yes

#824 Proxy config: Add tls_certs_to_watch field
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, ok-to-test

#825 Revert "Proxy config: Add tls_certs_to_watch field"
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: approved, cla: yes
