Repository istio/api, pull requests merged in 2019-10, with the labels that each got.

#1105 K8sCertificateSetting configures the provision of k8s CA signed certificates
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/M

#1111 Fix logic to test if 'make' needs to be run
  Makefile.core.mk
  authentication/v1alpha1/istio.authentication.v1alpha1.json
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  scripts/check-clean.sh
  security/v1beta1/authorization.json
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.proto
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cla: yes, size/M

#1113 Add a gen-check target.
  Makefile
  Makefile.core.mk
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/service_entry.pb.html
Labels: cla: yes, size/M

#1114 Fix the gen-check target
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#1085 feat(mixerclient): add field to ignore forwarded attributes
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.json
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
Labels: cla: yes, size/S

#1112 feat(mesh config): add support for disabling reporting via mixer
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/S

#1116 Adding target resources to annotations
  annotation/annotations.yaml
Labels: size/M

#1117 Spell check and Istio Style Guide conformance
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/M

#1119 Update common files.
  Makefile
  annotation/annotations.pb.html
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: cla: yes, size/XS

#1120 add API for ALPN filter
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.proto
  proto.lock
  python/istio_api/envoy/config/filter/http/alpn/v2alpha1/config_pb2.py
Labels: cla: yes, size/M

#1121 Update common files.
  Makefile
  annotation/annotations.gen.go
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  common/.commonfiles.sha
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.pb.html
  policy/v1beta1/istio.policy.v1beta1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  security/v1beta1/istio.security.v1beta1.pb.html
  type/v1beta1/istio.type.v1beta1.pb.html
Labels: cla: yes, size/S

#1122 Fix bad quote characters
  README.md
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/XS

#1124 Update common files.
  Makefile
  authentication/v1alpha1/istio.authentication.v1alpha1.json
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  common/.commonfiles.sha
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.json
  mixer/v1/config/client/istio.mixer.v1.config.client.json
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/istio.mixer.v1.json
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.json
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.json
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.json
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.json
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.pb.html
  policy/v1beta1/istio.policy.v1beta1.json
  policy/v1beta1/istio.policy.v1beta1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.json
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  security/v1beta1/istio.security.v1beta1.pb.html
  type/v1beta1/istio.type.v1beta1.pb.html
Labels: cla: yes, size/L

#1126 Fixed a few comment typos.
  rbac/v1alpha1/istio.rbac.v1alpha1.json
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: cla: yes, size/XS

#1127 Update go modules to use the latest patch releases
  go.mod
  go.sum
Labels: cla: yes, size/XS

#1132 Release 1.4 codeowners
  CODEOWNERS
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  mcp/Readme.md
  mixer/adapter/model/v1beta1/info.pb.go
  mixer/adapter/model/v1beta1/info.proto
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.json
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Labels: cla: yes, size/M

#1131 add release 1.4 protolock
  releaselocks/release-1.4/proto.lock
  releaselocks/release-1.4/proto.lock.status
Labels: cla: yes, size/XXL

#1110 security: do not generate envoy xds protos here
  Makefile.core.mk
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
Labels: cla: yes, size/S

#1133 Updated paths for networking docs.
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cherrypick/release-1.4, cla: yes, size/S

#1135 Fix bad alias syntax.
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cherrypick/release-1.4, cla: yes

#1136 [release-1.4] Fix bad alias syntax.
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, size/S

#1137 Fix URL references to account for moved content.
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cherrypick/release-1.4, cla: yes, size/S

#1138 [release-1.4] Fix URL references to account for moved content.
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, size/S

#1118 Remove unimplemented/unused labels in authn target selector
  authentication/v1alpha1/istio.authentication.v1alpha1.json
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  python/istio_api/authentication/v1alpha1/policy_pb2.py
Labels: cla: yes, size/S

#1143 Clarify connection pool example
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: cherrypick/release-1.4, cla: yes, size/S

#1145 Add backticks around sidecar doc symbols
  networking/v1alpha3/envoy_filter.json
  networking/v1alpha3/sidecar.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_deepcopy.gen.go
Labels: cla: yes, size/L

#1144 [release-1.4] Clarify connection pool example
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: cla: yes, size/S

#1142 Add CRD structural schema generation
  Makefile.core.mk
  README.md
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.proto
  cue.yaml
  kubernetes/customresourcedefinitions.gen.yaml
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
  policy/v1beta1/type.proto
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.proto
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cla: yes, size/XL

#1146 Update common files.
  Makefile
  Makefile.core.mk
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/check_clean_repo.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
  licenses/cloud.google.com/go/LICENSE
  licenses/github.com/BurntSushi/toml/COPYING
  licenses/github.com/client9/misspell/LICENSE
  licenses/github.com/gogo/protobuf/LICENSE
  licenses/github.com/golang/glog/LICENSE
  licenses/github.com/golang/mock/LICENSE
  licenses/github.com/golang/protobuf/LICENSE
  licenses/github.com/google/go-cmp/LICENSE
  licenses/github.com/kisielk/errcheck/LICENSE
  licenses/github.com/kisielk/gotool/LICENSE
  licenses/golang.org/x/crypto/LICENSE
  licenses/golang.org/x/lint/LICENSE
  licenses/golang.org/x/net/LICENSE
  licenses/golang.org/x/oauth2/LICENSE
  licenses/golang.org/x/sync/LICENSE
  licenses/golang.org/x/sys/LICENSE
  licenses/golang.org/x/text/LICENSE
  licenses/golang.org/x/tools/LICENSE
  licenses/google.golang.org/appengine/LICENSE
  licenses/google.golang.org/genproto/LICENSE
  licenses/google.golang.org/grpc/LICENSE
  licenses/honnef.co/go/tools/LICENSE
  licenses/istio.io/gogo-genproto/LICENSE
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.pb.html
  policy/v1beta1/istio.policy.v1beta1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cla: yes, size/XXL

#1147 [release-1.4] Add backticks around sidecar doc symbols
  networking/v1alpha3/envoy_filter.json
  networking/v1alpha3/sidecar.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_deepcopy.gen.go
Labels: cla: yes, size/L

#1149 Update common files.
  Makefile
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_clean_repo.sh
  common/scripts/report_build_info.sh
  licenses/cloud.google.com/go/LICENSE
  licenses/github.com/BurntSushi/toml/COPYING
  licenses/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING
  licenses/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING
  licenses/github.com/BurntSushi/toml/cmd/tomlv/COPYING
  licenses/github.com/client9/misspell/LICENSE
  licenses/github.com/gogo/protobuf/LICENSE
  licenses/github.com/golang/glog/LICENSE
  licenses/github.com/golang/mock/LICENSE
  licenses/github.com/golang/protobuf/LICENSE
  licenses/github.com/google/go-cmp/LICENSE
  licenses/github.com/kisielk/errcheck/LICENSE
  licenses/github.com/kisielk/gotool/LICENSE
  licenses/golang.org/x/crypto/LICENSE
  licenses/golang.org/x/lint/LICENSE
  licenses/golang.org/x/net/LICENSE
  licenses/golang.org/x/oauth2/LICENSE
  licenses/golang.org/x/sync/LICENSE
  licenses/golang.org/x/sys/LICENSE
  licenses/golang.org/x/text/LICENSE
  licenses/golang.org/x/tools/LICENSE
  licenses/golang.org/x/tools/cmd/getgo/LICENSE
  licenses/google.golang.org/appengine/LICENSE
  licenses/google.golang.org/genproto/LICENSE
  licenses/google.golang.org/grpc/LICENSE
  licenses/honnef.co/go/tools/LICENSE
  licenses/honnef.co/go/tools/gcsizes/LICENSE
  licenses/honnef.co/go/tools/lint/LICENSE
  licenses/honnef.co/go/tools/ssa/LICENSE
  licenses/istio.io/gogo-genproto/LICENSE
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.pb.html
  policy/v1beta1/istio.policy.v1beta1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cla: yes, size/XXL

#1141 Add locality load balancer settings on destination rule
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
Labels: cla: yes, ok-to-test, size/XL

#1140 Fix default doc for idle timeout
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: cla: yes, size/XS
