Repository istio/api, pull requests merged in 2019-12, with the labels that each got.

#1192 Use annotations for CRD gen
  Makefile
  annotation/annotations.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/report_build_info.sh
  cue.yaml
  kubernetes/customresourcedefinitions.gen.yaml
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/api_spec.proto
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/quota.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/XL

#1191 Even with permissive mode, the TLS require client cert
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  proto.lock
Labels: cla: yes, ok-to-test, size/L

#1194 Few small updates to the mesh config API
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, size/S

#1196 Remove field rules from api repo
  extensions/field_rules.proto
  proto.lock
Labels: cla: yes, size/XXL

#1200 update to individual owners - attempt to fix 2 approvers issue
  CODEOWNERS
Labels: cla: yes, size/XS

#1202 Fix some comments that were leading to bogus HTML.
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
Labels: cla: yes, size/M

#1172 Add forward spec to JWTRule
  kubernetes/customresourcedefinitions.gen.yaml
  proto.lock
  python/istio_api/security/v1beta1/jwt_pb2.py
  python/istio_api/security/v1beta1/request_authentication_pb2.py
  security/v1beta1/jwt.gen.json
  security/v1beta1/jwt.pb.go
  security/v1beta1/jwt.pb.html
  security/v1beta1/jwt.proto
  security/v1beta1/jwt_json.gen.go
  security/v1beta1/request_authentication.gen.json
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/M

#1207 common-files update master-2019-12-15T16-17-48
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: cla: yes, size/S

#1184 Fix deny all authorization policy examples
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.pb.html
  security/v1beta1/authorization.proto
  security/v1beta1/authorization_deepcopy.gen.go
  security/v1beta1/authorization_json.gen.go
Labels: cherrypick/release-1.4, cla: yes, ok-to-test, size/XS

#1189 deprecate consecutive_errors and add consecutive_gateway_errors & consecutive_5xx_errors
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: cla: yes, ok-to-test, size/M

#1210 Put back doc for gateways field in http match
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, size/S

#1193 Remove incorrect escape character.
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  rbac/v1alpha1/rbac_deepcopy.gen.go
  rbac/v1alpha1/rbac_json.gen.go
Labels: cla: yes, ok-to-test, size/XS

#1216 Partial revert of #1211
  Makefile.core.mk
  go.mod
  go.sum
  licenses/k8s.io/api/LICENSE
  mesh/v1alpha1/component.pb.go
  mesh/v1alpha1/component.proto.bak
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/kubernetes.pb.go
  mesh/v1alpha1/kubernetes.proto.bak
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/operator.pb.go
  mesh/v1alpha1/operator.proto.bak
  mesh/v1alpha1/proxy.pb.go
  proto.lock
Labels: cla: yes, size/XXL

#1217 Partial revert of #1211, part 2
  Makefile.core.mk
  go.mod
  go.sum
  licenses/github.com/NYTimes/gziphandler/LICENSE.md
  licenses/github.com/PuerkitoBio/purell/LICENSE
  licenses/github.com/PuerkitoBio/urlesc/LICENSE
  licenses/github.com/davecgh/go-spew/LICENSE
  licenses/github.com/docker/spdystream/LICENSE
  licenses/github.com/elazarl/goproxy/LICENSE
  licenses/github.com/emicklei/go-restful/LICENSE
  licenses/github.com/evanphx/json-patch/LICENSE
  licenses/github.com/fsnotify/fsnotify/LICENSE
  licenses/github.com/ghodss/yaml/LICENSE
  licenses/github.com/go-logr/logr/LICENSE
  licenses/github.com/go-openapi/jsonpointer/LICENSE
  licenses/github.com/go-openapi/jsonreference/LICENSE
  licenses/github.com/go-openapi/spec/LICENSE
  licenses/github.com/go-openapi/swag/LICENSE
  licenses/github.com/golang/groupcache/LICENSE
  licenses/github.com/google/gofuzz/LICENSE
  licenses/github.com/google/uuid/LICENSE
  licenses/github.com/googleapis/gnostic/LICENSE
  licenses/github.com/hashicorp/golang-lru/LICENSE
  licenses/github.com/hpcloud/tail/LICENSE.txt
  licenses/github.com/hpcloud/tail/ratelimiter/Licence
  licenses/github.com/json-iterator/go/LICENSE
  licenses/github.com/kr/pretty/License
  licenses/github.com/kr/pty/License
  licenses/github.com/kr/text/License
  licenses/github.com/mailru/easyjson/LICENSE
  licenses/github.com/modern-go/concurrent/LICENSE
  licenses/github.com/modern-go/reflect2/LICENSE
  licenses/github.com/munnerz/goautoneg/NONE
  licenses/github.com/mxk/go-flowrate/LICENSE
  licenses/github.com/onsi/ginkgo/LICENSE
  licenses/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable/LICENSE
  licenses/github.com/onsi/ginkgo/reporters/stenographer/support/go-isatty/LICENSE
  licenses/github.com/onsi/gomega/LICENSE
  licenses/github.com/pmezard/go-difflib/LICENSE
  licenses/github.com/spf13/pflag/LICENSE
  licenses/github.com/stretchr/objx/LICENSE
  licenses/github.com/stretchr/testify/LICENSE
  licenses/gopkg.in/check.v1/LICENSE
  licenses/gopkg.in/fsnotify.v1/LICENSE
  licenses/gopkg.in/inf.v0/LICENSE
  licenses/gopkg.in/tomb.v1/LICENSE
  licenses/gopkg.in/yaml.v2/LICENSE
  licenses/k8s.io/apimachinery/LICENSE
  licenses/k8s.io/gengo/LICENSE
  licenses/k8s.io/klog/LICENSE
  licenses/k8s.io/kube-openapi/LICENSE
  licenses/sigs.k8s.io/structured-merge-diff/LICENSE
  licenses/sigs.k8s.io/yaml/LICENSE
  mesh/v1alpha1/common.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
Labels: cla: yes, size/XXL

#1218 Change mixer CRDs to lower case
  kubernetes/customresourcedefinitions.gen.yaml
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
Labels: cla: yes, size/M
