Repository istio/api, pull requests merged in 2019-05, with the labels that each got.

#915 correct default values in the destination rule
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: approved, cla: yes, lgtm, ok-to-test

#914 adding report_batch_max_request and report_batch_max_time to TransportConfig
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  proto.lock
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
Labels: approved, cla: yes, lgtm

#922 Add issue templates like in istio/istio
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, cla: yes, lgtm

#921 Add a status field in QuotaResult
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.pb.html
  mixer/adapter/model/v1beta1/quota.pb.go
  mixer/adapter/model/v1beta1/quota.proto
  proto.lock
  python/istio_api/mixer/adapter/model/v1beta1/quota_pb2.py
Labels: approved, cla: yes, lgtm

#916 add default max connections to docs
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: approved, cla: yes, lgtm

#926 Add parameter to ignore HTTP match case
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: approved, cla: yes, lgtm

#919 improve code snippet style of MeshNetworks
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
Labels: approved, cla: yes, lgtm, ok-to-test

#920 Document default behavior for maxRequestsPerConnection
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: approved, cla: yes, lgtm, ok-to-test

#931 Update URL given new doc location.
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#929 adding fields to allow batch reporting options to be tunable as helm values
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: approved, cla: yes, lgtm

#934 Update URL given new doc location. (#931)
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm

#935 Import common files into this repo.
  .circleci/config.yml
  .commonfiles.sha
  .golangci.yml
  BUGS-AND-FEATURE-REQUESTS.md
  CONTRIBUTING.md
  LICENSE
  Makefile
  Makefile.common.mk
  README.md
  SUPPORT.md
  go.sum
  prow/api-presubmit.sh
  scripts/check-repositories
  scripts/check_license.sh
  scripts/generate-protos.sh
  scripts/pre-commit
  scripts/run_gofmt.sh
  scripts/run_golangci.sh
Labels: approved, cla: yes

#911 Adding envoy gRPC access log service configuration to MeshConfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, ok-to-test
