Repository istio/api, pull requests merged in 2019-09, with the labels that each got.

#1064 Correct some minor syntax errors
  mcp/Readme.md
Labels: cla: yes, size/XS

#1070 fix the sidecar egress order in the example
  networking/v1alpha3/sidecar.proto
Labels: cla: yes, size/XS

#1054 Typo fix for mesh config proto
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cherrypick/release-1.3, cla: yes, ok-to-test, size/XS

#1072 Typo fix for config.proto
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/XS

#1069 Fix typo
  mesh/v1alpha1/config.proto
  networking/v1alpha3/service_entry.proto
Labels: cherrypick/release-1.3, cla: yes, ok-to-test, size/XS

#941 fix spell mistake
  mixer/v1/mixer.pb.go
  mixer/v1/mixer.proto
Labels: cla: yes, ok-to-test, size/XS

#1077 Enable all linters on this repo.
  GUIDELINES.md
  Makefile.core.mk
  README.md
  common/.commonfiles.sha
  common/Makefile.common.mk
  mcp/Readme.md
  python/setup.py
  scripts/check-release-locks.md
  scripts/check-release-locks.sh
Labels: cla: yes, size/L

#1079 Add mirror_percent and deprecate mirror in HTTPRoute
  mixer/v1/istio.mixer.v1.json
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, size/S

#1084 xds: use standard proto for mixerclient config
  Makefile.core.mk
  go.mod
  go.sum
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/service.pb.go
Labels: cla: yes, size/XS

#987 correct sample of handler api
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.pb.html
Labels: area/policies and telemetry, cla: yes, size/M

#1087 Restore Mixer client to use gogo code gen.
  Makefile.core.mk
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/service.pb.go
Labels: cla: yes, size/S

#1088 Fix envoy protos to use golang protos
  Makefile.core.mk
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
Labels: cla: yes, size/XS

#1089 Revert "Fix envoy protos to use golang protos"
  Makefile.core.mk
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
Labels: cla: yes, size/XS

#1091 Fix EnvoyFilter example
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: cla: yes, size/XS

#1083 Add synthetic serviceEntry option to config source
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/XXL

#1092 Fix missing right quote
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, ok-to-test, size/XS

#1078 refine NetworkEndpoints fromRegistry field description
  mesh/v1alpha1/network.proto
Labels: area/networking, cla: yes, kind/docs, ok-to-test, size/XS

#1093 Update common files and common protos
  Makefile
  common-protos/.commonfiles.sha
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/any.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/api.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/compiler/plugin.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/descriptor.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/duration.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/empty.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/field_mask.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/source_context.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/struct.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/timestamp.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/type.proto
  common-protos/github.com/gogo/protobuf/protobuf/google/protobuf/wrappers.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_code.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_code_proto2.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_explicit_legacy.proto
  common-protos/google/protobuf/compiler/ruby/ruby_generated_pkg_implicit.proto
  common-protos/k8s.io/api/admissionregistration/v1/generated.proto
  common-protos/k8s.io/api/admissionregistration/v1beta1/generated.proto
  common-protos/k8s.io/api/apps/v1/generated.proto
  common-protos/k8s.io/api/apps/v1beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta1/generated.proto
  common-protos/k8s.io/api/autoscaling/v2beta2/generated.proto
  common-protos/k8s.io/api/batch/v1/generated.proto
  common-protos/k8s.io/api/batch/v1beta1/generated.proto
  common-protos/k8s.io/api/batch/v2alpha1/generated.proto
  common-protos/k8s.io/api/coordination/v1/generated.proto
  common-protos/k8s.io/api/coordination/v1beta1/generated.proto
  common-protos/k8s.io/api/core/v1/generated.proto
  common-protos/k8s.io/api/events/v1beta1/generated.proto
  common-protos/k8s.io/api/networking/v1beta1/generated.proto
  common-protos/k8s.io/api/node/v1alpha1/generated.proto
  common-protos/k8s.io/api/node/v1beta1/generated.proto
  common-protos/k8s.io/api/policy/v1beta1/generated.proto
  common-protos/k8s.io/api/scheduling/v1/generated.proto
  common-protos/k8s.io/api/scheduling/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1/generated.proto
  common-protos/k8s.io/api/storage/v1alpha1/generated.proto
  common-protos/k8s.io/api/storage/v1beta1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/api/resource/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  common-protos/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/gobuild.sh
  common/scripts/lint_go.sh
  common/scripts/report_build_info.sh
  proto.lock
Labels: cla: yes, size/XXL

#1090 Add an annotation option to opt-in autopilot.
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/XS

#1097 Fix build process.
  Makefile.core.mk
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
Labels: cla: yes, size/XS

#1098 Fix retry policy links
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, size/XS

#1100 removed port name from the port selector
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, size/M

#1102 Add check to make sure 'make' has been run on the repo before checkin.
  Makefile.core.mk
Labels: cla: yes, size/S

#1099 [release-1.3] Fix retry policy links
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, size/XS

#1106 Update common files.
  Makefile
  common-protos/.commonfiles.sha
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/gobuild.sh
  go.mod
Labels: cla: yes, size/L

#1107 Update to latest gogo.
  authentication/v1alpha1/policy.pb.go
  go.mod
  go.sum
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/service.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service_json.gen.go
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/http_response.pb.go
  policy/v1beta1/type.pb.go
  policy/v1beta1/value_type.pb.go
  rbac/v1alpha1/rbac.pb.go
  security/v1beta1/authorization.pb.go
Labels: cla: yes, size/S

#1108 Doc for VirtualService sourceLabels field
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cherrypick/release-1.3, cla: yes, size/XS

#1109 Add trust_domain_aliases
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  mcp/v1alpha1/mcp.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  mixer/adapter/model/v1beta1/check.pb.go
  mixer/adapter/model/v1beta1/extensions.pb.go
  mixer/adapter/model/v1beta1/info.pb.go
  mixer/adapter/model/v1beta1/infrastructure_backend.pb.go
  mixer/adapter/model/v1beta1/quota.pb.go
  mixer/adapter/model/v1beta1/report.pb.go
  mixer/adapter/model/v1beta1/template.pb.go
  mixer/v1/attributes.pb.go
  mixer/v1/mixer.pb.go
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  type/v1beta1/selector.pb.go
Labels: cla: yes, size/M
