Repository istio/api, pull requests merged in 2019-04, with the labels that each got.

#883 Add configuration for matching on query params
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes

#885 Add role to ServiceRoleBinding API to essentially replace roleRef later
  proto.lock
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: approved, cla: yes, lgtm

#892 add Greg Hanson as reviewer/approver to istio/api repo
  OWNERS
Labels: cla: yes

#891 Adding idle_timeout field to DestinationRule
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: cla: yes, ok-to-test

#887 Fixes istio/istio#12873. Add field Sidecar.OutboundTrafficPolicy to o…
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  proto.lock
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
Labels: cla: yes, ok-to-test

#894 Revert Github #887 (SHA cf912ceffb25353871734e526c8ae099827b2823)
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  proto.lock
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
Labels: approved, cla: yes

#896 Add idle_timeout field to DestinationRule
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: cla: yes, lgtm, ok-to-test

#898 Sidecar Capture mode NONE to use Bind API changes
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: cla: yes, ok-to-test

#901 Clarify doc for VirtualService gateways field
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes

#903 Add warning about sidecar egress
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: approved, cla: yes, lgtm

#886 Correct percentage value to match 1 out of 1000 docs value
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm, ok-to-test

#904 update the default of maxRetries in DestinationRule to 1024
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: cla: yes

#874 update host desc that more than one vs share same host
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: approved, cla: yes, lgtm
