Repository istio/api, pull requests merged in 2019-11, with the labels that each got.

#1157 Regen with new container for release 1.4
  Makefile
  Makefile.core.mk
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  authentication/v1alpha1/policy_json.gen.go
  common/.commonfiles.sha
  mcp/v1alpha1/istio.mcp.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.gen.json
  mixer/v1/attributes_json.gen.go
  mixer/v1/config/client/api_spec_json.gen.go
  mixer/v1/config/client/client_config_json.gen.go
  mixer/v1/config/client/istio.mixer.v1.config.client.gen.json
  mixer/v1/config/client/quota_json.gen.go
  mixer/v1/config/client/service_json.gen.go
  mixer/v1/istio.mixer.v1.gen.json
  mixer/v1/mixer_json.gen.go
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule_json.gen.go
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter_json.gen.go
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway_json.gen.go
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar_json.gen.go
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service_json.gen.go
  policy/v1beta1/cfg_json.gen.go
  policy/v1beta1/http_response_json.gen.go
  policy/v1beta1/istio.policy.v1beta1.gen.json
  policy/v1beta1/type_json.gen.go
  rbac/v1alpha1/istio.rbac.v1alpha1.gen.json
  rbac/v1alpha1/rbac_json.gen.go
  security/v1beta1/authorization.gen.json
  security/v1beta1/authorization_json.gen.go
  type/v1beta1/selector.gen.json
  type/v1beta1/selector_json.gen.go
Labels: cla: yes, size/M

#1158 update the RBAC and authz doc for 1.4
  kubernetes/customresourcedefinitions.gen.yaml
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  rbac/v1alpha1/rbac_deepcopy.gen.go
  rbac/v1alpha1/rbac_json.gen.go
  security/v1beta1/authorization.proto
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cherrypick/release-1.4, cla: yes, size/XS

#1159 [release-1.4]: update the RBAC and authz doc for 1.4
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  rbac/v1alpha1/rbac_deepcopy.gen.go
  rbac/v1alpha1/rbac_json.gen.go
  security/v1beta1/authorization.proto
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: area/security, cla: yes, size/XS

#1160 Add operator annotations
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/S

#1161 [release-1.4] Add operator annotations
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/S

#1162 Gen for annotations
  Makefile
  annotation/annotations.gen.go
  common/.commonfiles.sha
Labels: cla: yes, size/S

#1163 Regen with 1.4 container
  Makefile
  Makefile.core.mk
  authentication/v1alpha1/istio.authentication.v1alpha1.json
  authentication/v1alpha1/policy_deepcopy.gen.go
  common/.commonfiles.sha
  mcp/v1alpha1/istio.mcp.v1alpha1.json
  mesh/v1alpha1/istio.mesh.v1alpha1.json
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.json
  mixer/v1/config/client/api_spec_deepcopy.gen.go
  mixer/v1/config/client/istio.mixer.v1.config.client.json
  mixer/v1/config/client/quota_deepcopy.gen.go
  mixer/v1/istio.mixer.v1.json
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/envoy_filter.json
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/gateway.json
  networking/v1alpha3/gateway_deepcopy.gen.go
  networking/v1alpha3/service_entry.json
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/sidecar.json
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/virtual_service.json
  networking/v1alpha3/virtual_service_deepcopy.gen.go
  policy/v1beta1/cfg_deepcopy.gen.go
  policy/v1beta1/istio.policy.v1beta1.json
  rbac/v1alpha1/istio.rbac.v1alpha1.json
  rbac/v1alpha1/rbac_deepcopy.gen.go
  security/v1beta1/authorization.json
  security/v1beta1/authorization_deepcopy.gen.go
  type/v1beta1/selector.json
Labels: cla: yes, size/M

#1164 Generate with new container
  Makefile
  annotation/annotations.gen.go
  authentication/v1alpha1/policy_deepcopy.gen.go
  common/.commonfiles.sha
  mixer/v1/config/client/api_spec_deepcopy.gen.go
  mixer/v1/config/client/quota_deepcopy.gen.go
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/gateway_deepcopy.gen.go
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/virtual_service_deepcopy.gen.go
  policy/v1beta1/cfg_deepcopy.gen.go
  rbac/v1alpha1/rbac_deepcopy.gen.go
  security/v1beta1/authorization_deepcopy.gen.go
Labels: cla: yes, size/XS

#1139 Disable circuit breaking by default
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: cherrypick/release-1.4, cla: yes, ok-to-test, size/S

#1165 Reorganize reference docs
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.proto
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.proto
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cherrypick/release-1.4, cla: yes, size/S

#1166 [release-1.4] Disable circuit breaking by default
  networking/v1alpha3/destination_rule.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: cla: yes, size/S

#1167 Manual cherry-pick #1165
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.proto
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.proto
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cla: yes, size/S

#1151 Add RequestAuthetication API
  Makefile.core.mk
  python/istio_api/security/v1beta1/jwt_pb2.py
  python/istio_api/security/v1beta1/request_authentication_pb2.py
  security/v1beta1/authorization.gen.json
  security/v1beta1/authorization.pb.html
  security/v1beta1/jwt.gen.json
  security/v1beta1/jwt.pb.go
  security/v1beta1/jwt.pb.html
  security/v1beta1/jwt.proto
  security/v1beta1/jwt_json.gen.go
  security/v1beta1/request_authentication.gen.json
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  security/v1beta1/request_authentication_json.gen.go
Labels: cla: yes, size/L

#1169 Add RequestAuthentication to CRD gen
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  cue.yaml
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/authorization.gen.json
  security/v1beta1/request_authentication.gen.json
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  security/v1beta1/request_authentication_deepcopy.gen.go
Labels: cla: yes, size/M

#1168 Fix documentation for RequestAuthentication
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/XS

#1170 Fix broken aliases
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.proto
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.pb.html
  security/v1beta1/authorization.proto
  security/v1beta1/jwt.proto
  security/v1beta1/request_authentication.proto
Labels: cherrypick/release-1.4, cla: yes, size/S

#1171 Fix broken aliases (manual cherry-pick of #1170)
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.proto
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.proto
  security/v1beta1/istio.security.v1beta1.pb.html
Labels: cla: yes, size/S

#1176 Use different example in api guidelines
  GUIDELINES.md
Labels: cla: yes, size/XS

#1173 VirtualService: use a double for mirror_percent
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, ok-to-test, size/M

#1181 Fix broken link
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cla: yes, size/XS

#1180 Docs for namespace of VirtualService gateways
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  proto.lock
Labels: cla: yes, ok-to-test, size/L

#1186 Add istio api extensions definitions
  extensions/field_rules.proto
Labels: cla: yes, size/M

#1185 Clarify location of timeout field
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: cherrypick/release-1.4, cla: yes, size/S
