Repository istio/api, pull requests merged in 2020-03, with the labels that each got.

#1292 update docs for stats patterns
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/S

#1305 Fix front matter generation in some API docs (#1295)
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  security/v1beta1/jwt.gen.json
  security/v1beta1/jwt.pb.html
  security/v1beta1/jwt.proto
  security/v1beta1/peer_authentication.gen.json
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.gen.json
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/M

#1306 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#1296 Add status port to proxy config
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, size/XS

#1308 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#1304 Add short name for RequestAuthentication and PeerAuthentication
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/XS

#1310 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#1311 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#1312 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#1313 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#1309 cherry pick 1263 to release 1.5 branch
  Makefile.core.mk
  operator/v1alpha1/operator.proto
  operator/v1alpha1/operator_deepcopy.gen.go
  operator/v1alpha1/operator_json.gen.go
  proto.lock
Labels: cla: yes, size/S

#1315 Update envoyfilter
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: cla: yes, size/XS

#1317 Automator: update common-files@master in istio/api@master
  .gitignore
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#1318 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#1319 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#1320 Fix MeshConfig field tags for JSON unmarshal
  Makefile.core.mk
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/proxy.pb.go
Labels: cherrypick/release-1.5, cla: yes, size/XS

#1322 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#1323 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1325 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#1324 Fix bug with JSON tag camelCase conversion
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/proxy.pb.go
  operator/fixup_structs/main.go
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/operator.pb.go
Labels: cherrypick/release-1.5, cla: yes, size/S

#1328 [1.5] Fix bug with JSON tag camelCase conversion (#1324)
  operator/fixup_structs/main.go
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/operator.pb.go
Labels: cla: yes, size/S

#1321 [1.5] Fix MeshConfig field tags for JSON unmarshal (#1320)
  Makefile.core.mk
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/proxy.pb.go
Labels: cla: yes, size/XS

#1327 Update ECMAscript to RE2
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  authentication/v1alpha1/policy.proto
  kubernetes/customresourcedefinitions.gen.yaml
  mixer/v1/config/client/api_spec.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.gen.json
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/config/client/quota.proto
  mixer/v1/istio.mixer.v1.gen.json
  mixer/v1/mixer.pb.go
  mixer/v1/mixer.proto
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.proto
Labels: cla: yes, ok-to-test, size/M

#1336 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#1337 Tag must be interface{} type for unmarshaling (#1275)
  Makefile.core.mk
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/component.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/component_pb2.py
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, size/S

#1338 Use golang protobuf in operator json generated code (#1283)
  Makefile.core.mk
  operator/v1alpha1/operator_json.gen.go
Labels: cla: yes, size/XS

#1330 revert #1248 - sidecar inboundTls
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/sidecar_json.gen.go
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/sidecar_deepcopy.gen.go
  networking/v1beta1/sidecar_json.gen.go
  proto.lock
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
  python/istio_api/networking/v1beta1/sidecar_pb2.py
Labels: cla: yes, size/L

#1339 feat(label): add label package
  label/label.go
Labels: cla: yes, size/S

#1340 Add Josh to master code owner list
  CODEOWNERS
Labels: cla: yes, size/XS

#1334 cleanup gateway SDS documentation
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
Labels: cla: yes, size/M

#1332 cleanup unused and incorrect annotations
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/M

#1341 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1343 add more details for TCP connection timeout description
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.pb.html
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  policy/v1beta1/istio.policy.v1beta1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  security/v1beta1/authorization.pb.html
  security/v1beta1/jwt.pb.html
  security/v1beta1/peer_authentication.pb.html
Labels: cla: yes, ok-to-test, size/XS

#1342 Add UNSPECIFIED option for ingress mode
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  releaselocks/release-1.0/proto.lock.status
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
  releaselocks/release-1.5/proto.lock.status
Labels: cla: yes, size/M

#1344 Remove old envoyfilter fields
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_json.gen.go
  networking/v1alpha3/service_entry.gen.json
  proto.lock
  python/istio_api/networking/v1alpha3/envoy_filter_pb2.py
  releaselocks/release-1.0/proto.lock.status
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
  releaselocks/release-1.5/proto.lock.status
Labels: cla: yes, size/XL

#1347 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1348 Automator: update common-files@release-1.5 in istio/api@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#1349 Generate with latest build tool
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.gen.json
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/istio.mixer.v1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.html
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/virtual_service.gen.json
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  policy/v1beta1/istio.policy.v1beta1.gen.json
  policy/v1beta1/istio.policy.v1beta1.pb.html
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  security/v1beta1/authorization.pb.html
  security/v1beta1/peer_authentication.pb.html
Labels: cla: yes, size/XXL

#1350 Generate 1.5 API with new build tool
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.gen.json
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  mixer/v1/istio.mixer.v1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.html
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/virtual_service.gen.json
  policy/v1beta1/istio.policy.v1beta1.gen.json
  policy/v1beta1/istio.policy.v1beta1.pb.html
Labels: cla: yes, size/XXL

#1345 Fix comment indent
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/M

#1346 Document new sidecar annotations for setting resource limits
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, ok-to-test, size/S

#1331 VMs: Separate endpoints from service entry into WorkloadEntry
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/workload_entry.gen.json
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_entry.proto
  networking/v1alpha3/workload_entry_deepcopy.gen.go
  networking/v1alpha3/workload_entry_json.gen.go
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  networking/v1beta1/service_entry_deepcopy.gen.go
  networking/v1beta1/service_entry_json.gen.go
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/workload_entry.gen.json
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  networking/v1beta1/workload_entry_deepcopy.gen.go
  networking/v1beta1/workload_entry_json.gen.go
  proto.lock
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
  python/istio_api/networking/v1alpha3/workload_entry_pb2.py
  python/istio_api/networking/v1beta1/service_entry_pb2.py
  python/istio_api/networking/v1beta1/workload_entry_pb2.py
  releaselocks/release-1.0/proto.lock.status
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
  releaselocks/release-1.5/proto.lock.status
Labels: cla: yes, size/XXL

#1351 Hide v1alpha1 RBAC and Authentication policy
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  kubernetes/customresourcedefinitions.gen.yaml
  rbac/v1alpha1/istio.rbac.v1alpha1.gen.json
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
Labels: cla: yes, size/S

#1353 Fix WorkloadEntry CRD
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
Labels: cla: yes, size/XS

#1352 Remove redundant connect timeout
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, size/XS

#1333 Localhost TLS termination and initiation in Sidecar
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/destination_rule_json.gen.go
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/gateway_json.gen.go
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_json.gen.go
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/destination_rule_json.gen.go
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/gateway_json.gen.go
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/sidecar_json.gen.go
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1alpha3/gateway_pb2.py
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/gateway_pb2.py
  python/istio_api/networking/v1beta1/sidecar_pb2.py
  releaselocks/release-1.0/proto.lock.status
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
  releaselocks/release-1.5/proto.lock.status
Labels: cla: yes, size/XXL

#1359 Adding ClusterLocalNamespaces to mesh config
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/S
