Repository istio/api, pull requests merged in 2020-08, with the labels that each got.

#1568 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1569 Automator: update common-files@release-1.7 in istio/api@release-1.7
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1572 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1573 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1567 Fix quantity and lock down others to a more specific type
  operator/v1alpha1/common.go
  operator/v1alpha1/common_test.go
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cherrypick/release-1.7, cla: yes, size/L

#1579 [Manual Cherry-Pick] Fix quantity and lock down others to a more specific type (#1567)
  operator/v1alpha1/common.go
  operator/v1alpha1/common_test.go
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, size/L

#1575 Change meshId type to string
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, size/XS

#1580 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1581 Change status timestamp to protobuf timestamp
  meta/v1alpha1/status.gen.json
  meta/v1alpha1/status.pb.go
  meta/v1alpha1/status.pb.html
  meta/v1alpha1/status.proto
  meta/v1alpha1/status_deepcopy.gen.go
  meta/v1alpha1/status_json.gen.go
  proto.lock
  python/istio_api/meta/v1alpha1/status_pb2.py
Labels: cla: yes, size/M

#1582 [release-1.7] Change status timestamp to protobuf timestamp
  meta/v1alpha1/status.gen.json
  meta/v1alpha1/status.pb.go
  meta/v1alpha1/status.pb.html
  meta/v1alpha1/status.proto
  meta/v1alpha1/status_deepcopy.gen.go
  meta/v1alpha1/status_json.gen.go
  proto.lock
  python/istio_api/meta/v1alpha1/status_pb2.py
Labels: cla: yes, size/M

#1583 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1584 Automator: update common-files@release-1.7 in istio/api@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1587 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#1563 tracing: add API for OpenCensus agent exporter
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, ok-to-test, size/L

#1576 Add metadata field into Istio CertificateSigningService
  Makefile.core.mk
  proto.lock
  python/istio_api/security/v1alpha1/ca_pb2.py
  security/v1alpha1/ca.gen.json
  security/v1alpha1/ca.pb.go
  security/v1alpha1/ca.proto
  security/v1alpha1/ca_deepcopy.gen.go
  security/v1alpha1/ca_json.gen.go
Labels: cla: yes, ok-to-test, size/M

#1554 WorkloadGroup CRD
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/workload_group.gen.json
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.pb.html
  networking/v1alpha3/workload_group.proto
  networking/v1alpha3/workload_group_deepcopy.gen.go
  networking/v1alpha3/workload_group_json.gen.go
  python/istio_api/networking/v1alpha3/workload_group_pb2.py
Labels: cla: yes, ok-to-test, size/L

#1589 add pod securitycontext for operator api.
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cherrypick/release-1.6, cherrypick/release-1.7, cla: yes, size/L

#1595 [release-1.6]add pod securitycontext for operator api.
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/component.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/kubernetes.pb.go
  operator/v1alpha1/kubernetes.proto
  proto.lock
  python/istio_api/operator/v1alpha1/component_pb2.py
  python/istio_api/operator/v1alpha1/kubernetes_pb2.py
Labels: cla: yes, size/L

#1594 [release-1.7]add pod securitycontext for operator api.
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, size/L

#1597 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1588 Define FilterClasses with REPLACE
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
  python/istio_api/networking/v1alpha3/envoy_filter_pb2.py
Labels: cla: yes, size/L

#1585 Add VerifyCertificateAtClient to MeshConfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cherrypick/release-1.7, cla: yes, size/M

#1601 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1600 update envoy filter docs
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: cla: yes, size/M

#1604 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1591 tracing: remove uncommonly-used tuning configs
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, ok-to-test, size/M

#1606 clarify HTTP requests timeout default
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: cla: yes, size/XS

#1596 Added MeshConfig for Custom External CA
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, ok-to-test, size/M

#1610 Fix escape in gateway docs
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
Labels: cla: yes, size/XS

#1611 Remove policy and telemetry component from operator API
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, size/XS

#1612 Update mesh id type to string
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, size/XS
