Repository istio/api, pull requests merged in 2020-07, with the labels that each got.

#1495 Update CRDs to v1
  Makefile.core.mk
  kubernetes/customresourcedefinitions.gen.yaml
  scripts/validate_crds.py
Labels: cla: yes, size/L

#1493 Specify defaults for mesh and proxy configs
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: cla: yes, size/M

#1497 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1498 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1472 [release-1.6] Fix missing Headers doc
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: cla: yes, size/XS

#1501 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1500 Add preserveUnknownFields to EnvoyFilter
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
Labels: cla: yes, size/XS

#1477 Add targetPort to ServiceEntry Port
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/workload_entry.gen.json
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_entry.proto
  networking/v1alpha3/workload_entry_deepcopy.gen.go
  networking/v1alpha3/workload_entry_json.gen.go
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/workload_entry.gen.json
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  networking/v1beta1/workload_entry_deepcopy.gen.go
  networking/v1beta1/workload_entry_json.gen.go
  proto.lock
  python/istio_api/networking/v1alpha3/gateway_pb2.py
  python/istio_api/networking/v1beta1/gateway_pb2.py
Labels: cla: yes, size/L

#1502 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#1506 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1505 Automator: update common-files@release-1.6 in istio/api@release-1.6
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#1507 Generate x-kubernetes-preserve-unknown-fields at EnvoyFilter field level
  kubernetes/customresourcedefinitions.gen.yaml
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/api_spec.proto
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/quota.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.proto
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/S

#1512 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#1516 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#1515 fix gateways typo
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: cla: yes, ok-to-test, size/XS

#1449 Add Status types to API
  Makefile.core.mk
  analysis/v1alpha1/message.gen.json
  analysis/v1alpha1/message.pb.go
  analysis/v1alpha1/message.pb.html
  analysis/v1alpha1/message.proto
  cue.yaml
  meta/v1alpha1/status.gen.json
  meta/v1alpha1/status.pb.go
  meta/v1alpha1/status.pb.html
  meta/v1alpha1/status.proto
  proto.lock
  python/istio_api/analysis/v1alpha1/message_pb2.py
  python/istio_api/meta/v1alpha1/status_pb2.py
Labels: cla: yes, size/XL

#1517 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1518 Replace/remove "whitelist" in comments/descriptions
  mixer/v1/mixer.proto
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  policy/v1beta1/istio.policy.v1beta1.gen.json
  policy/v1beta1/istio.policy.v1beta1.pb.html
Labels: cla: yes, size/S

#1509 Remove extraneous file.
  istio.mesh.v1alpha1.pb.html
Labels: cherrypick/release-1.6, cla: yes, size/XS

#1519 Add x-kubernetes-preserve-unknown-fields to instances and handlers
  annotation/annotations.gen.go
  kubernetes/customresourcedefinitions.gen.yaml
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
Labels: cla: yes, size/XS

#1523 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#1526 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/S

#1527 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#1521 [release-1.6] Remove extraneous file.
  istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/XS

#1525 Fix gateway selection documentation
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
Labels: cla: yes, size/M

#1524 remove hide from docs instruction in meta/status
  meta/v1alpha1/status.pb.html
  meta/v1alpha1/status.proto
Labels: cla: yes, size/XS

#1529 Remove unimplemented Sidecar Localhost APIs
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/sidecar_json.gen.go
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/sidecar_deepcopy.gen.go
  networking/v1beta1/sidecar_json.gen.go
  proto.lock
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
  python/istio_api/networking/v1beta1/sidecar_pb2.py
  releaselocks/release-1.6/proto.lock.status
Labels: cla: yes, size/XL

#1532 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1534 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1535 Fix link so istio.io linter passes (remove latest)
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: cla: yes, size/XS

#1537 Gateway CA certs can be stored in secret-cacert
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
Labels: cla: yes, size/XS

#1499 add pending to operator status
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, size/M

#1538 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#1543 Remove the CA proto files from security/v1beta1.
  security/v1beta1/ca.pb.go
  security/v1beta1/ca_deepcopy.gen.go
  security/v1beta1/ca_json.gen.go
Labels: cla: yes, size/XS

#1540 Fix invalid link for WorkloadSelector
  security/v1beta1/authorization.pb.html
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/request_authentication.pb.html
  type/v1beta1/istio.type.v1beta1.pb.html
  type/v1beta1/selector.proto
Labels: cla: yes, size/XS

#1533 Add generated functions to status and analysis APIs
  Makefile.core.mk
  analysis/v1alpha1/message_deepcopy.gen.go
  analysis/v1alpha1/message_json.gen.go
  meta/v1alpha1/status_deepcopy.gen.go
  meta/v1alpha1/status_json.gen.go
Labels: cla: yes, size/S

#1544 Set release managers as CODEOWNERS for release-1.7
  CODEOWNERS
Labels: cla: yes, size/XS

#1549 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#1547 Updates for 1.7
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
  mixer/adapter/model/v1beta1/info.pb.go
  mixer/adapter/model/v1beta1/info.proto
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.gen.json
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Labels: cla: yes, size/S

#1553 Automator: update common-files@release-1.7 in istio/api@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1550 Fix broken link for WorkloadSelector
  security/v1beta1/authorization.pb.html
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/request_authentication.pb.html
  type/v1beta1/selector.proto
Labels: cla: yes, size/XS

#1556 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1558 Fix broken link for WorkloadSelector 1.7
  security/v1beta1/authorization.pb.html
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/request_authentication.pb.html
  type/v1beta1/selector.proto
Labels: cla: yes, kind/docs, size/XS

#1557 Fix broken link for WorkloadSelector 1.6
  security/v1beta1/authorization.pb.html
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/request_authentication.pb.html
  type/v1beta1/istio.type.v1beta1.pb.html
  type/v1beta1/selector.proto
Labels: cla: yes, kind/docs, size/XS

#1545 Add nrjpoddar as API repo code owner
  CODEOWNERS
Labels: cla: yes, size/XS

#1560 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1561 Add allowed_trust_domains for the authn filter config.
  envoy/config/filter/http/authn/v2alpha1/config.proto
  python/istio_api/envoy/config/filter/http/authn/v2alpha1/config_pb2.py
Labels: cla: yes, size/S

#1546 pod label for network
  label/label.go
Labels: cla: yes, size/XS

#1564 remove more mixer stuff
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, size/L

#1552 Extend authorization policy action with 'Audit' action
  kubernetes/customresourcedefinitions.gen.yaml
  proto.lock
  python/istio_api/security/v1beta1/authorization_pb2.py
  security/v1beta1/authorization.gen.json
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.pb.html
  security/v1beta1/authorization.proto
  security/v1beta1/authorization_deepcopy.gen.go
  security/v1beta1/authorization_json.gen.go
Labels: cla: yes, ok-to-test, size/L

#1562 Tweak locality lb docs a bit
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: cla: yes, size/S
