Repository istio/api, pull requests merged in 2020-05, with the labels that each got.

#1415 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#1416 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#1366 Align operator API with reality
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/component.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  python/istio_api/operator/v1alpha1/component_pb2.py
Labels: cla: yes, size/XS

#1417 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1419 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1421 Automator: update common-files@release-1.6 in istio/api@release-1.6
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1420 Add preserveUnknownFields to CRDs
  kubernetes/customresourcedefinitions.gen.yaml
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/api_spec.proto
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/quota.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.proto
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/S

#1422 [release-1.6]Add preserveUnknownFields to CRDs
  kubernetes/customresourcedefinitions.gen.yaml
  mixer/v1/config/client/api_spec.pb.go
  mixer/v1/config/client/api_spec.proto
  mixer/v1/config/client/quota.pb.go
  mixer/v1/config/client/quota.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.proto
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/S

#1418 Change proxyConfig.concurrency to wrapper
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
  releaselocks/release-1.5/proto.lock.status
Labels: cla: yes, size/L

#1423 Remove preserveUnknownFields from EnvoyFilter
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
Labels: cherrypick/release-1.6, cla: yes, size/XS

#1424 [release-1.6] Remove preserveUnknownFields from EnvoyFilter
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
Labels: cla: yes, size/XS

#1426 Update CRDs to not validate status field
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  kubernetes/customresourcedefinitions.gen.yaml
Labels: cla: yes, size/XS

#1429 Automator: update common-files@release-1.6 in istio/api@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1428 Add istiod remote to component proto
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/component.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  python/istio_api/operator/v1alpha1/component_pb2.py
Labels: cla: yes, size/XS

#1430 [release-1.6]Update CRDs to not validate status field
  kubernetes/customresourcedefinitions.gen.yaml
Labels: cla: yes, size/XS

#1433 Fix grammar issue
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_entry.proto
  networking/v1alpha3/workload_entry_deepcopy.gen.go
  networking/v1alpha3/workload_entry_json.gen.go
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  networking/v1beta1/workload_entry_deepcopy.gen.go
  networking/v1beta1/workload_entry_json.gen.go
Labels: cla: yes, size/XS

#1434 Automator: update common-files@release-1.5 in istio/api@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#1437 Hide localhost TLS unimplemented APIs
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
Labels: cherrypick/release-1.6, cla: yes, size/XS

#1438 [release-1.6] Hide localhost TLS unimplemented APIs
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
Labels: cla: yes, size/XS

#1436 Add release 1.6 release lock
  releaselocks/release-1.6/proto.lock
  releaselocks/release-1.6/proto.lock.status
Labels: cla: yes, size/XXL

#1427 authz: remove alpha RBAC API
  Makefile.core.mk
  cue.yaml
  kubernetes/customresourcedefinitions.gen.yaml
  proto.lock
  prototool.yaml
  python/istio_api/rbac/v1alpha1/rbac_pb2.py
  rbac/v1alpha1/istio.rbac.v1alpha1.gen.json
  rbac/v1alpha1/istio.rbac.v1alpha1.pb.html
  rbac/v1alpha1/rbac.pb.go
  rbac/v1alpha1/rbac.proto
  rbac/v1alpha1/rbac_deepcopy.gen.go
  rbac/v1alpha1/rbac_json.gen.go
  releaselocks/release-1.0/proto.lock.status
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
  releaselocks/release-1.5/proto.lock.status
  releaselocks/release-1.6/proto.lock.status
Labels: cla: yes, size/XXL

#1440 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1441 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1445 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#1439 fix envoy filter doc indentation error
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: cla: yes, size/XS

#1448 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#1446 Add selector to Ingress
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/api_spec_deepcopy.gen.go
  mixer/v1/config/client/quota_deepcopy.gen.go
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/gateway_deepcopy.gen.go
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/virtual_service_deepcopy.gen.go
  networking/v1alpha3/workload_entry_deepcopy.gen.go
  networking/v1beta1/destination_rule_deepcopy.gen.go
  networking/v1beta1/gateway_deepcopy.gen.go
  networking/v1beta1/service_entry_deepcopy.gen.go
  networking/v1beta1/sidecar_deepcopy.gen.go
  networking/v1beta1/virtual_service_deepcopy.gen.go
  networking/v1beta1/workload_entry_deepcopy.gen.go
  operator/v1alpha1/operator_deepcopy.gen.go
  policy/v1beta1/cfg_deepcopy.gen.go
  python/istio_api/mesh/v1alpha1/config_pb2.py
  security/v1beta1/authorization_deepcopy.gen.go
  security/v1beta1/peer_authentication_deepcopy.gen.go
  security/v1beta1/request_authentication_deepcopy.gen.go
Labels: cherrypick/release-1.6, cla: yes, size/S
