Repository istio/api, pull requests merged in 2020-01, with the labels that each got.

#1206 Deprecate obsolete fields in authN alpha policy.
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  authentication/v1alpha1/istio.authentication.v1alpha1.pb.html
  authentication/v1alpha1/policy.pb.go
  authentication/v1alpha1/policy.proto
  kubernetes/customresourcedefinitions.gen.yaml
  python/istio_api/authentication/v1alpha1/policy_pb2.py
Labels: cla: yes, size/M

#1219 Add kubeType annotation for mixer CRD client registration
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
Labels: cherrypick/release-1.4, cla: yes, size/XS

#1224 [release-1.4] Add kubeType annotation for mixer CRD client registration
  policy/v1beta1/cfg.pb.go
  policy/v1beta1/cfg.proto
Labels: cla: yes, size/XS

#1182 add enable for locality lb setting
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
Labels: cla: yes, ok-to-test, size/XXL

#1226 Add annotation for enableCoreDump
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, ok-to-test, size/XS

#1228 Fix link errors in authorization policy
  security/v1beta1/authorization.gen.json
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.pb.html
  security/v1beta1/authorization.proto
  type/v1beta1/istio.type.v1beta1.pb.html
  type/v1beta1/selector.proto
Labels: cla: yes, size/S

#1197 add StringMatcher in CorsPolicy
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, ok-to-test, size/M

#1214 Remove some fields in virtualservice
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, size/L

#1230 add service annotation to KubernetesResourcesSpec in operator api.
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/component.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  proto.lock
  python/istio_api/operator/v1alpha1/component_pb2.py
Labels: cla: yes, size/S

#1222 add deny and negative match in authorization policy
  kubernetes/customresourcedefinitions.gen.yaml
  proto.lock
  python/istio_api/security/v1beta1/authorization_pb2.py
  security/v1beta1/authorization.gen.json
  security/v1beta1/authorization.pb.go
  security/v1beta1/authorization.pb.html
  security/v1beta1/authorization.proto
  security/v1beta1/authorization_deepcopy.gen.go
  security/v1beta1/authorization_json.gen.go
Labels: cla: yes, size/L

#1231 move status out of spec for operator api
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, size/M

#1227 Add annotation for suppressing analyzer messages per-resource
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/S

#1229 use custom type for k8s intorstring for operator
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/kubernetes.pb.go
  operator/v1alpha1/kubernetes.proto
  proto.lock
  python/istio_api/operator/v1alpha1/kubernetes_pb2.py
Labels: cla: yes, size/S

#1235 Initial thrift configuration
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, ok-to-test, size/S

#1233 Add the HeaderMatch field and type for supporting all the header match types of Envoy
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, ok-to-test, size/S

#1236 fix toleration type for operator
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/component.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/kubernetes.pb.go
  operator/v1alpha1/kubernetes.proto
  proto.lock
  python/istio_api/operator/v1alpha1/component_pb2.py
  python/istio_api/operator/v1alpha1/kubernetes_pb2.py
Labels: cla: yes, size/M

#1238 clarify acceptable values for protocolDetectionTimeout
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/XS

#1234 Add option INSERT_FIRST in EnvoyFilter.Patch.Operation
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  python/istio_api/networking/v1alpha3/envoy_filter_pb2.py
Labels: cla: yes, size/S

#1240 Release 1.5 common files update
  Makefile
  common-protos/.commonfiles.sha
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#1246 cherry-pick of #1085
  Makefile.core.mk
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.json
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  proto.lock
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
Labels: cla: yes, size/M

#1239 Reference thrift config in MeshConfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, ok-to-test, size/S

#1250 Revert "Add without_headers field to HTTPMatchRequest for specifying …
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, size/S

#1251 Mirror HorizontalPodAutoscalerSpec to fix overlay issue
  operator/v1alpha1/component.pb.go
  operator/v1alpha1/component.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/kubernetes.pb.go
  operator/v1alpha1/kubernetes.proto
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/component_pb2.py
  python/istio_api/operator/v1alpha1/kubernetes_pb2.py
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, size/L

#1257 [release-1.5] Revert "Add without_headers field to HTTPMatchRequest for specifying …
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, size/S

#1247 Update EnvoyFilter API docs
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: cla: yes, size/S

#1256 Release 1.5 codeowners
  CODEOWNERS
  common/Makefile.common.mk
  mcp/Readme.md
  mixer/adapter/model/v1beta1/info.pb.go
  mixer/adapter/model/v1beta1/info.proto
  mixer/adapter/model/v1beta1/istio.mixer.adapter.model.v1beta1.gen.json
  mixer/v1/attributes.pb.go
  mixer/v1/attributes.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Labels: cla: yes, size/S

#1259 cherry-pick of https://github.com/istio/api/pull/1085
  mixer/v1/config/client/client_config.pb.go
  mixer/v1/config/client/client_config.proto
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
Labels: cla: yes, size/S

#1258 Add release-1.5 protolock
  operator/fixup_structs/main.go
  releaselocks/release-1.5/proto.lock
  releaselocks/release-1.5/proto.lock.status
Labels: cla: yes, size/XXL

#1262 Cherry-pick 1dffc8d3d26d
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  proto.lock
  python/istio_api/mixer/v1/config/client/client_config_pb2.py
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
Labels: cla: yes, size/L

#1261 [release-1.5] Update EnvoyFilter API docs
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: cla: yes, size/S

#1255 Sync between v1alpha3 and v1beta1 and add back reverted commit
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.pb.html
  networking/v1beta1/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
  python/istio_api/networking/v1beta1/virtual_service_pb2.py
Labels: cla: yes, size/S

#1241 Peer authentication beta API, aka mTLS beta
  kubernetes/customresourcedefinitions.gen.yaml
  proto.lock
  python/istio_api/security/v1beta1/peer_authentication_pb2.py
  security/v1beta1/peer_authentication.gen.json
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
  security/v1beta1/peer_authentication_deepcopy.gen.go
  security/v1beta1/peer_authentication_json.gen.go
Labels: cla: yes, size/L

#1265 Update common
  LICENSE
  Makefile
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1beta1/destination_rule.pb.html
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  policy/v1beta1/istio.policy.v1beta1.pb.html
  security/v1beta1/authorization.pb.html
Labels: cla: yes, size/M

#1264 Update common file to 1.5 branch
  LICENSE
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#1266 Add networking v1beta1 example to docs
  Makefile.core.mk
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/destination_rule_json.gen.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/gateway_deepcopy.gen.go
  networking/v1alpha3/gateway_json.gen.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/sidecar_json.gen.go
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/virtual_service_deepcopy.gen.go
  networking/v1alpha3/virtual_service_json.gen.go
  networking/v1beta1/destination_rule.pb.html
  networking/v1beta1/gateway.pb.html
  networking/v1beta1/service_entry.pb.html
  networking/v1beta1/sidecar.pb.html
  networking/v1beta1/virtual_service.pb.html
Labels: cla: yes, size/XXL

#1267 [release-1.5] Add networking v1beta1 example to docs
  Makefile
  Makefile.core.mk
  common/.commonfiles.sha
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mixer/v1/config/client/istio.mixer.v1.config.client.pb.html
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/destination_rule_json.gen.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/gateway_deepcopy.gen.go
  networking/v1alpha3/gateway_json.gen.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/sidecar_json.gen.go
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/virtual_service_deepcopy.gen.go
  networking/v1alpha3/virtual_service_json.gen.go
  networking/v1beta1/destination_rule.pb.html
  networking/v1beta1/gateway.pb.html
  networking/v1beta1/service_entry.pb.html
  networking/v1beta1/sidecar.pb.html
  networking/v1beta1/virtual_service.pb.html
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  policy/v1beta1/istio.policy.v1beta1.pb.html
  security/v1beta1/authorization.pb.html
Labels: cla: yes, size/XXL
