Repository istio/api, pull requests merged in 2021-10, with the labels that each got.

#2111 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2109 update protoc version
  python/istio_api/analysis/v1alpha1/message_pb2.py
  python/istio_api/authentication/v1alpha1/policy_pb2.py
  python/istio_api/extensions/v1alpha1/wasm_pb2.py
  python/istio_api/mcp/v1alpha1/mcp_pb2.py
  python/istio_api/mcp/v1alpha1/metadata_pb2.py
  python/istio_api/mcp/v1alpha1/resource_pb2.py
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/network_pb2.py
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  python/istio_api/meta/v1alpha1/status_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1alpha3/envoy_filter_pb2.py
  python/istio_api/networking/v1alpha3/gateway_pb2.py
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
  python/istio_api/networking/v1alpha3/workload_entry_pb2.py
  python/istio_api/networking/v1alpha3/workload_group_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/gateway_pb2.py
  python/istio_api/networking/v1beta1/service_entry_pb2.py
  python/istio_api/networking/v1beta1/sidecar_pb2.py
  python/istio_api/networking/v1beta1/virtual_service_pb2.py
  python/istio_api/networking/v1beta1/workload_entry_pb2.py
  python/istio_api/operator/v1alpha1/operator_pb2.py
  python/istio_api/security/v1alpha1/ca_pb2.py
  python/istio_api/security/v1beta1/authorization_policy_pb2.py
  python/istio_api/security/v1beta1/jwt_pb2.py
  python/istio_api/security/v1beta1/peer_authentication_pb2.py
  python/istio_api/security/v1beta1/request_authentication_pb2.py
  python/istio_api/telemetry/v1alpha1/telemetry_pb2.py
  python/istio_api/type/v1beta1/selector_pb2.py
Labels: cla: yes, size/XS, release-notes-none

#2105 support x-jwt-claim in request authentication
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/M

#2020 Fix config_source in EnvoyFilter docstring
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: cla: yes, size/XS, release-notes-none

#2112 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2114 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: cla: yes, size/S, auto-merge, release-notes-none

#2084 Add support for Envoy's connection type LOGICAL_DNS in ServiceEntry
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  python/istio_api/networking/v1alpha3/service_entry_pb2.py
  python/istio_api/networking/v1beta1/service_entry_pb2.py
  releasenotes/notes/support-logical-dns-connection-type.yaml
Labels: cla: yes, size/M

#2115 remove the doc for configuring sni-dnat
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
Labels: cla: yes, size/XS, release-notes-none

#2107 Move istio/proxy protos into istio/api
  buf.gen-golang.yaml
  envoy/README.md
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.proto
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.proto
  envoy/extensions/stats/config.pb.go
  envoy/extensions/stats/config.proto
  gen.sh
  go.mod
Labels: cla: yes, size/L, release-notes-none
