Repository istio/api, pull requests merged in 2021-05, with the labels that each got.

#1964 Change snake_case to camelCase for yaml documentation
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#1967 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1969 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1970 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1977 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1981 Add path_normalization API (#4)
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: cla: yes, release-notes-none, size/M

#1983 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1963 [release-1.10] Clarify docs and correct spaces
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, release-notes-none, size/S

#1949 [release-1.10] Fix BoolValueForPB.GetValue allow nil
  operator/v1alpha1/common.go
  operator/v1alpha1/common_test.go
Labels: cla: yes, release-notes-none, size/M

#1982 Security fix on URL normalization (GoldPanda).
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  releasenotes/notes/url-normalization.yaml
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/M

#1985 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1986 Security fix on URL normalization (GoldPanda).
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  releasenotes/notes/url-normalization.yaml
Labels: cla: yes, size/M

#1990 Update protolock
  proto.lock
Labels: cherrypick/release-1.10, cla: yes, release-notes-none, size/M

#1989 add local origin error configuration to destination rules
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
  releasenotes/notes/32645.yaml
Labels: cla: yes, size/M

#1994 rename field in local origin errors
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
Labels: cla: yes, release-notes-none, size/S

#1996 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1987 [release-1.10] Document annotations used for injection
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, release-notes-none, size/S

#2001 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1998 Document how to configure proxy config
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: cla: yes, release-notes-none, size/S

#2005 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2006 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2007 Automator: update common-files@master in istio/api@master
  analysis/v1alpha1/message.gen.json
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  kubernetes/customresourcedefinitions.gen.yaml
  mcp/v1alpha1/istio.mcp.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  meta/v1alpha1/status.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/workload_entry.gen.json
  networking/v1alpha3/workload_group.gen.json
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/workload_entry.gen.json
  security/v1alpha1/ca.gen.json
  security/v1beta1/authorization_policy.gen.json
  security/v1beta1/jwt.gen.json
  security/v1beta1/peer_authentication.gen.json
  security/v1beta1/request_authentication.gen.json
  type/v1beta1/selector.gen.json
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2008 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#2009 Add extra note about workload restart for proxy config
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: cla: yes, release-notes-none, size/XS

#2010 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1974 envoyfilter: add bootstrap patch
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
  python/istio_api/networking/v1alpha3/envoy_filter_pb2.py
Labels: cla: yes, release-notes-none, size/M

#2011 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
