Repository istio/api, pull requests merged in 2021-01, with the labels that each got.

#1789 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1791 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1790 Fix rendering for proxyMetadata
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: cla: yes, release-notes-none, size/XS

#1723 Specify feature status for annotations
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, release-notes-none, size/M

#1793 Shriram is no longer a part of the TOC
  CODEOWNERS
Labels: cla: yes, release-notes-none, size/XS

#1805 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#1807 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1808 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1804 Add documentation for labels
  Makefile.core.mk
  annotation/annotations.gen.go
  annotation/annotations.yaml
  go.sum
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
Labels: cla: yes, release-notes-none, size/L

#1811 Updating description for canonical service labels.
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
Labels: cla: yes, release-notes-none, size/XS

#1770 Mark port as required field for health check
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.pb.html
  networking/v1alpha3/workload_group.proto
  python/istio_api/networking/v1alpha3/workload_group_pb2.py
Labels: cla: yes, release-notes-none, size/XS

#1781 Cleanup generated files that we no longer generate
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  python/istio_api/mesh/v1alpha1/component_pb2.py
  python/istio_api/mesh/v1alpha1/kubernetes_pb2.py
  python/istio_api/mesh/v1alpha1/operator_pb2.py
  python/istio_api/operator/v1alpha1/component_pb2.py
  python/istio_api/operator/v1alpha1/kubernetes_pb2.py
  python/istio_api/security/v1beta1/ext_authz_pb2.py
Labels: cla: yes, release-notes-none, size/XS

#1819 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1820 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1822 Generate protos
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  mcp/v1alpha1/mcp.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/workload_entry.pb.go
  proto.lock
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/jwt.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  type/v1beta1/selector.pb.go
Labels: cla: yes, release-notes-none, size/M

#1824 Update common/Makefile.common.mk to use release-1.9
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#1825 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1823 Set release managers as CODEOWNERS for release-1.9
  CODEOWNERS
Labels: cla: yes, size/XS

#1826 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1827 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none

#1828 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1816 Use gogo/protobuf 1.3.2
  go.mod
  go.sum
  licenses/istio.io/gogo-genproto/LICENSE
Labels: cla: yes, release-notes-none, size/M

#1829 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none, size/XS

#1832 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1821 Update makefile for new docs plugin
  Makefile.core.mk
  authentication/v1alpha1/policy.proto
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  mesh/v1alpha1/config.proto
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/gateway.proto
  networking/v1beta1/service_entry.proto
  networking/v1beta1/sidecar.proto
  networking/v1beta1/virtual_service.proto
  networking/v1beta1/workload_entry.proto
  operator/v1alpha1/operator.proto
Labels: cla: yes, release-notes-none, size/M

#1835 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#1786 fix request authentication comment
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cherrypick/release-1.8, cla: yes, size/XS

#1836 [release-1.8] fix request authentication comment
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, release-notes-none, size/XS

#1838 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1840 Automator: update common-files@master in istio/api@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1841 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1839 Removing unused labels.
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  label/label.go
Labels: cla: yes, release-notes-none, size/M

#1843 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#1844 Add CRD labels to WorkloadGroup
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.proto
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, release-notes-none, size/XS

#1846 [release-1.9] Add CRD labels to WorkloadGroup
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.proto
Labels: cla: yes, release-notes-none, size/XS

#1845 [release-1.8] Add CRD labels to WorkloadGroup
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.proto
Labels: cla: yes, release-notes-none, size/XS

#1847 Automator: update common-files@release-1.8 in istio/api@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#1856 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1855 Fix MeshNetworks example documentation
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
Labels: cla: yes, ok-to-test, size/XS

#1857 Automator: update common-files@release-1.7 in istio/api@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1858 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1861 Workaround golang bug causing make gen to fail
  Makefile.core.mk
Labels: cla: yes, release-notes-none, size/XS

#1853 Updating initial stability of subzone and network labels
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
Labels: cla: yes, release-notes-none, size/XS

#1865 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS
