Repository istio/api, pull requests merged in 2021-07, with the labels that each got.

#2021 Add tooling to automatically sync proto versions
  gen.sh
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  proto.lock
  releaselocks/release-1.6/proto.lock.status
  scripts/check-release-locks.md
  scripts/check-release-locks.sh
  scripts/sync.sh
Labels: cla: yes, release-notes-none, size/L

#2044 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1766 Add support to Telemetry API for metrics and access logging
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/telemetry/v1alpha1/telemetry_pb2.py
  releasenotes/notes/add-experimental-telemetry-api-for-metrics-logging.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: cla: yes, size/L

#2046 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2048 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2049 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2050 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2052 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2051 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2053 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2054 [release-1.11] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#2059 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2060 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2062 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2063 Automator: update common-files@release-1.11 in istio/api@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2065 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1940 Add WasmPlugin API
  buf.yaml
  cue.yaml
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  extensions/v1alpha1/wasm_deepcopy.gen.go
  extensions/v1alpha1/wasm_json.gen.go
  gen.sh
  kubernetes/customresourcedefinitions.gen.yaml
  python/istio_api/extensions/v1alpha1/wasm_pb2.py
  releasenotes/notes/add-wasm-extensions-api.yaml
Labels: cla: yes, size/L

#2040 Introduce InsecureSkipVerify to DR
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
  releasenotes/notes/25652.yaml
Labels: cla: yes, size/L
