Repository istio/api, pull requests merged in 2021-06, with the labels that each got.

#1955 docs: clear sourceLabels
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: area/test and release, cla: yes, release-notes-none, size/XS

#2017 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2019 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2018 Remove istiodRemote component
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, release-notes-none, size/XS

#1975 Add explicit order to patch sets.
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  python/istio_api/networking/v1alpha3/envoy_filter_pb2.py
Labels: cla: yes, release-notes-none, size/S

#2023 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2026 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2027 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2024 Updated CODEOWNERS to reflect the surviving TOC
  CODEOWNERS
Labels: cla: yes, release-notes-none, size/XS

#2029 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2031 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#2022 Updated clusterMatch docs
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  proto.lock
Labels: cla: yes, release-notes-none, size/M

#2030 Components for remote and config cluster installations.
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, release-notes-none, size/S

#2034 fix the html issue of unescaped < character
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/M

#2035 release-1.9: fix the html issue of unescaped < character
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/S

#2039 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#2037 Update TOC codeowners
  CODEOWNERS
Labels: cla: yes, release-notes-none, size/XS

#2025 Fix jwt rule note
  security/v1beta1/jwt.pb.go
  security/v1beta1/jwt.pb.html
  security/v1beta1/jwt.proto
Labels: cla: yes, release-notes-none, size/XS

#1968 Use RE2 instead of ECMAscript regex-based match
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: cla: yes, release-notes-none, size/S

#2042 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
