Repository istio/api, pull requests merged in 2021-08, with the labels that each got.

#2066 fix `credential_name` documentation
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: cla: yes, release-notes-none, size/XS

#2064 Fix docs for telemetry
  kubernetes/customresourcedefinitions.gen.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: cla: yes, release-notes-none, size/XS

#2070 Update envoy TLS configuration link
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: cherrypick/release-1.11, cla: yes, release-notes-none, size/S

#2073 [release-1.11] Update envoy TLS configuration link
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: cla: yes, release-notes-none, size/S

#2074 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2043 General topology aware loadbalancing
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
Labels: cla: yes, size/L, release-notes-none

#2075 Automator: update common-files@release-1.11 in istio/api@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2058 Add global HTTP retry policy API in MeshConfig
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  python/istio_api/mesh/v1alpha1/config_pb2.py
  releasenotes/notes/default-http-retry-policy.yaml
Labels: cla: yes, size/S

#2077 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2079 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2078 Fix for istio.io linter
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
Labels: cla: yes, size/XS, release-notes-none

#2081 hide deprecated `mirror_percent` from docs
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  proto.lock
Labels: cla: yes, size/S

#2085 Update `failoverPriority` comments
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: cla: yes, size/S

#2061 Add new guidelines to API compatibility
  GUIDELINES.md
Labels: cla: yes, size/M, release-notes-none
