Repository istio/api, pull requests merged in 2021-11, with the labels that each got.

#2130 move annotation to istio/api
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, ok-to-test, size/M, release-notes-none

#2137 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2104 add option to skip sidecar generated requestID based sampling decision
  kubernetes/customresourcedefinitions.gen.yaml
  python/istio_api/telemetry/v1alpha1/telemetry_pb2.py
  releasenotes/notes/skip_request_id_sampling.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.proto
Labels: cla: yes, size/S

#2139 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2140 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2141 Unhide default_http_retry_policy now that it is implemented
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/XS, release-notes-none, cherrypick/release-1.12

#2143 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2134 update jwt based routing
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/S, cherrypick/release-1.12

#2145 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2144 [release-1.12] update jwt based routing
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/S, release-notes-none

#2142 [release-1.12] Unhide default_http_retry_policy now that it is implemented
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, size/XS, release-notes-none

#2147 Revert "Add ProxyConfig CRD (#2080)"
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1beta1/proxy_config.gen.json
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.proto
  networking/v1beta1/proxy_config_deepcopy.gen.go
  networking/v1beta1/proxy_config_json.gen.go
  python/istio_api/networking/v1beta1/proxy_config_pb2.py
  releasenotes/notes/proxy-config.yaml
Labels: cla: yes, size/L, release-notes-none

#2150 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: cla: yes, size/M, auto-merge, release-notes-none

#2151 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2155 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2148 Add ProxyImage to defaultConfig
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  networking/v1beta1/proxy_config.gen.json
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.proto
  networking/v1beta1/proxy_config_deepcopy.gen.go
  networking/v1beta1/proxy_config_json.gen.go
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  python/istio_api/networking/v1beta1/proxy_config_pb2.py
Labels: cla: yes, size/M, release-notes-none

#2157 Automator: update common-files@release-1.11 in istio/api@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2162 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S, auto-merge, release-notes-none

#2158 Add ProxyImage to defaultConfig (hidden)
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: cla: yes, size/S, release-notes-none

#2110 telemetry: add provider-specific format options
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/telemetry/v1alpha1/telemetry_pb2.py
  releasenotes/notes/add-access-logging-filter.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: cla: yes, size/L

#2163 Fix docs for WASM and Telemtry
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  extensions/v1alpha1/wasm_deepcopy.gen.go
  extensions/v1alpha1/wasm_json.gen.go
  kubernetes/customresourcedefinitions.gen.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: cla: yes, size/S, release-notes-none, cherrypick/release-1.12

#2164 [release-1.12] Fix docs for WASM and Telemtry
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  extensions/v1alpha1/wasm_deepcopy.gen.go
  extensions/v1alpha1/wasm_json.gen.go
  kubernetes/customresourcedefinitions.gen.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: cla: yes, size/S, release-notes-none

#2168 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2169 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2138 Align ProxyConfig merge semantics with other Istio resources
  networking/v1beta1/proxy_config.proto
Labels: cla: yes, size/S, release-notes-none

#2154 doc: fix selector in Wasm Plugin examples.
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  extensions/v1alpha1/wasm_deepcopy.gen.go
  extensions/v1alpha1/wasm_json.gen.go
Labels: cla: yes, size/XS, release-notes-none
