Repository istio/api, pull requests merged in 2021-03, with the labels that each got.

#1898 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1901 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1900 Update CRDs to v1
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
Labels: cla: yes, release-notes-none, size/XS

#1904 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1899 [release-1.9] Manual cherrypick of #1885
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/gateway_deepcopy.gen.go
  networking/v1alpha3/gateway_json.gen.go
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.pb.html
  networking/v1alpha3/workload_group.proto
  networking/v1alpha3/workload_group_deepcopy.gen.go
  networking/v1alpha3/workload_group_json.gen.go
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/gateway_deepcopy.gen.go
  networking/v1beta1/gateway_json.gen.go
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
  python/istio_api/networking/v1beta1/sidecar_pb2.py
  scripts/validate.sh
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/authorization_policy_deepcopy.gen.go
  security/v1beta1/authorization_policy_json.gen.go
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, release-notes-none, size/L

#1910 clean up mixer reference in sidecar API
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
Labels: cla: yes, size/S

#1911 Fixing docs for cluster_local defaults.
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, release-notes-none, size/XS

#1913 Minor grammar fix
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: cla: yes, release-notes-none, size/XS

#1915 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1916 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1907 Fix broken link for AuthorizationPolicy
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: cla: yes, release-notes-none, size/XS

#1894 Add more info if custom ns is used to install Istio
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
Labels: cla: yes, release-notes-none, size/XS

#1921 [release-1.9] Add more info if custom ns is used to install Istio
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
Labels: cla: yes, release-notes-none, size/XS

#1914 unhide bind in gateway api
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  releasenotes/notes/gateway-bind.yaml
Labels: cla: yes, size/S

#1919 Fix broken links for locations
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: cla: yes, release-notes-none, size/XS

#1740 Add initial Telemetry API with Tracing support for sampling and custom tags
  gen.sh
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/telemetry/v1alpha1/telemetry_pb2.py
  releasenotes/notes/add-experimental-telemetry-api-for-tracing.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: cla: yes, lifecycle/automatically-closed, size/L

#1929 Adjust VirtualService documentation format
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: cla: yes, release-notes-none, size/M

#1928 Add info about `portLevelMtls` requirement of workload selector with PeerAuthentication
  security/v1beta1/peer_authentication.gen.json
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
Labels: cla: yes, size/XS

#1933 add dry-run annotation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, release-notes-none, size/XS
