Repository istio/api, pull requests merged in 2021-04, with the labels that each got.

#1895 Fix AuthorizationPolicy Doc
  security/v1beta1/authorization_policy.gen.json
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: cla: yes, ok-to-test, release-notes-none, size/XS

#1926 update the ext-authz extension provider and promote to alpha
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/authorization_policy_deepcopy.gen.go
  security/v1beta1/authorization_policy_json.gen.go
Labels: cla: yes, size/L

#1903 Add sidecar.istio.io/agentLogLevel annotation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  releasenotes/notes/31248.yaml
Labels: cla: yes, size/S

#1934 Use wrapper types for Tracing fields
  kubernetes/customresourcedefinitions.gen.yaml
  python/istio_api/telemetry/v1alpha1/telemetry_pb2.py
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: cla: yes, release-notes-none, size/XS

#1935 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1936 change ext-authz feature to experimental
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: cla: yes, size/XS

#1941 [release-1.10] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: cla: yes, release-notes-none, size/XS

#1942 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1943 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1944 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1945 Automator: update common-files@release-1.8 in istio/api@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1946 Update common files in `master` branch
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: cla: yes, release-notes-none, size/XS

#1947 Pick up missed automator common-files update
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: cla: yes, release-notes-none, size/XS

#1939 Fix BoolValueForPB.GetValue allow nil
  operator/v1alpha1/common.go
  operator/v1alpha1/common_test.go
Labels: cla: yes, release-notes-none, size/M

#1950 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1951 Fix extra space in DR example
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: cla: yes, release-notes-none, size/M

#1909 add Apache SkyWalking tracer support
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  releasenotes/notes/skywalking-support.yaml
Labels: cla: yes, size/S

#1953 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1954 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1958 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#1960 fix meshnetworks example
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
Labels: cla: yes, size/XS

#1961 fix meshnetworks example
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
Labels: cla: yes, size/XS

#1952 fix incorrect type for maxUnavailable/minAvailable of PDB.
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  python/istio_api/operator/v1alpha1/operator_pb2.py
Labels: cla: yes, release-notes-none, size/XL

#1962 Clarify docs and correct spaces
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: cla: yes, release-notes-none, size/S

#1956 Document annotations used for injection
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, release-notes-none, size/S
