Repository istio/api, pull requests merged in 2021-09, with the labels that each got.

#2083 update api docs for retriable status codes
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: cla: yes, size/S, release-notes-none

#2091 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2089 add disable_clear_route_cache to the internal authn filter config
  envoy/config/filter/http/authn/v2alpha1/config.proto
Labels: cla: yes, size/XS

#2092 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2093 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2095 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2088 Add scheme and port to redirect
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  python/istio_api/networking/v1alpha3/virtual_service_pb2.py
  python/istio_api/networking/v1beta1/virtual_service_pb2.py
Labels: cla: yes, size/M, release-notes-none

#2098 Automator: update common-files@release-1.9 in istio/api@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2099 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2100 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2076 update cluster label docs
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
Labels: cla: yes, size/S, release-notes-none

#2086 Clarify request authentication root namespace scope.
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: cla: yes, size/S, release-notes-none

#2101 Automator: update common-files@release-1.11 in istio/api@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2103 Automator: update common-files@release-1.10 in istio/api@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2102 docs: Use fromHeaders instead of jwtHeaders field in JWTRule example
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/jwt.gen.json
  security/v1beta1/jwt.pb.go
  security/v1beta1/jwt.pb.html
  security/v1beta1/jwt.proto
  security/v1beta1/request_authentication.gen.json
Labels: cla: yes, ok-to-test, size/S

#2096 update docs for source ip support with tcp
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: cla: yes, release-notes-none
