Repository istio/api, pull requests merged in 2021-12, with the labels that each got.

#2172 [release-1.12] doc: fix selector in Wasm Plugin examples.
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  extensions/v1alpha1/wasm_deepcopy.gen.go
  extensions/v1alpha1/wasm_json.gen.go
Labels: cla: yes, size/XS, release-notes-none

#2176 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2180 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#2152 update authz and JWT documentation
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/authorization_policy.gen.json
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/authorization_policy_deepcopy.gen.go
  security/v1beta1/authorization_policy_json.gen.go
  security/v1beta1/request_authentication.gen.json
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: size/L, cherrypick/release-1.12

#2184 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2182 remove derelict/broken bazel build files
  BUILD
  WORKSPACE
Labels: ok-to-test, size/S, release-notes-none

#2167 Enable generation for ProxyConfig docs
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.pb.html
  networking/v1beta1/proxy_config.proto
  networking/v1beta1/proxy_config_deepcopy.gen.go
  networking/v1beta1/proxy_config_json.gen.go
Labels: cla: yes, size/XS, release-notes-none

#2186 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2188 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2183 [release-1.12] update authz and JWT documentation
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/authorization_policy.gen.json
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/authorization_policy_deepcopy.gen.go
  security/v1beta1/authorization_policy_json.gen.go
  security/v1beta1/request_authentication.gen.json
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: size/L, release-notes-none

#2179 unhide the dry-run annotation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: cla: yes, size/XS

#2189 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2190 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2194 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2193 move port label to api repo
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: ok-to-test, size/XS

#2192 Loosen weight validation
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: size/S, release-notes-none

#2195 fix telemetry doc
  releasenotes/notes/fix-telemetry-doc.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: size/S
