Repository istio/api, pull requests merged in 2022-09, with the labels that each got.

#2471 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2465 [release-1.14] Fix typo SKPI->SPKI
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/sidecar.gen.json
Labels: size/S, release-notes-none

#2472 Automator: update common-files@release-1.15 in istio/api@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2412 Add a match scheme to WasmPlugin for passing more specific traffic to Wasm module
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.proto
  extensions/v1alpha1/wasm_deepcopy.gen.go
  extensions/v1alpha1/wasm_json.gen.go
  kubernetes/customresourcedefinitions.gen.yaml
  type/v1beta1/selector.gen.json
  type/v1beta1/selector.pb.go
  type/v1beta1/selector.pb.html
  type/v1beta1/selector.proto
  type/v1beta1/selector_deepcopy.gen.go
  type/v1beta1/selector_json.gen.go
Labels: size/M, release-notes-none

#2473 Automator: update common-files@release-1.14 in istio/api@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2474 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2476 Fix the comments explaining Workload mode of gateways
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.proto
Labels: size/XS, release-notes-none

#2478 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2479 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2480 tracing: add warnings about OpenCensus configuration
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: size/S, release-notes-none

#2481 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2483 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2484 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2485 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#2487 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2486 Added `sidecar.istio.io/inject` label
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
Labels: size/S, release-notes-none

#2482 Update ConfigSource.address examples in docs
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: size/XS, needs-ok-to-test

#2489 fix CODEOWNERS
  CODEOWNERS
Labels: size/XS, release-notes-none

#2490 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
