Repository istio/api, pull requests merged in 2022-06, with the labels that each got.

#2370 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#2366 [release-1.14] fix proxy-config reference doc
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1beta1/proxy_config.gen.json
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.pb.html
  networking/v1beta1/proxy_config.proto
Labels: size/XS, release-notes-none

#2369 Bump dependencies
  go.mod
  go.sum
  licenses/github.com/google/go-cmp/LICENSE
Labels: size/L, release-notes-none

#2305 move node selector annotation to api repo
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: ok-to-test, size/S, release-notes-none

#2371 Fix broken DR documentation
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: size/XS, release-notes-none

#2373 [release-1.14] Fix broken DR documentation
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: size/XS, release-notes-none

#2336 Extends the scope of ImagePullPolicy to cover http[s]:// and file:// as …
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
Labels: ok-to-test, size/M, release-notes-none

#2377 Automator: update common-files@release-1.14 in istio/api@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2378 Fix description for warmup.
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: size/XS, release-notes-none

#2379 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2380 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2374 Document new sidecar annotation to exclude interfaces
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  releasenotes/notes/2374.yaml
Labels: ok-to-test, size/S

#2381 Make tunnel protocol not required
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: ok-to-test, size/XS

#2383 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2387 [release-1.14] Update DR indentation with workload selector
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: size/M, release-notes-none

#2389 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2390 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2391 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2394 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2395 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2396 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2399 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2400 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#2402 Fix typo fiter -> filter in EnvoyFilter documentation
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: ok-to-test, size/XS

#2385 Namespace annotation for cluster leaders
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  releasenotes/notes/39157.yaml
Labels: size/S

#2404 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
