Repository istio/api, pull requests merged in 2022-05, with the labels that each got.

#2337 Automator: update common-files@master in istio/api@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2338 Document auto_sni behaviour
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: size/XS, release-notes-none, cherrypick/release-1.14

#2339 [release-1.14] Document auto_sni behaviour
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: size/XS, release-notes-none

#2273 bump k8s hpa api mirrored in operator api to v2beta2
  go.mod
  go.sum
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  releasenotes/notes/deprecate-autoscaling-v2beta1.yaml
Labels: size/XL, cherrypick/release-1.14

#2340 [release-1.14] bump k8s hpa api mirrored in operator api to v2beta2
  go.mod
  go.sum
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
  releasenotes/notes/deprecate-autoscaling-v2beta1.yaml
Labels: size/XL, release-notes-none

#2344 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2345 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#2343 Hide verification_key from documentation
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
Labels: size/S, release-notes-none

#2347 Automator: update common-files@release-1.14 in istio/api@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2346 [release-1.14] Hide verification_key from documentation
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
Labels: size/S, release-notes-none

#2348 Automator: update common-files@release-1.13 in istio/api@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2349 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2351 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2354 Fix API rendering issue in ServiceEntry.Resolution
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
Labels: ok-to-test, size/XS, release-notes-none, cherrypick/release-1.14

#2356 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2357 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2355 [release-1.14] Fix API rendering issue in ServiceEntry.Resolution
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
Labels: size/XS, release-notes-none

#2358 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2360 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/XS, auto-merge, release-notes-none

#2361 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/XS, auto-merge, release-notes-none

#2362 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2363 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2365 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2367 Require uppercase value of tunnel protocol
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: ok-to-test, size/XS
