Repository istio/api, pull requests merged in 2022-02, with the labels that each got.

#2229 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2202 Add NONE mode to interception mode
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
Labels: size/XS, release-notes-none

#2220 clarify multiple tokens case for request authentication API
  security/v1beta1/jwt.pb.go
  security/v1beta1/jwt.pb.html
  security/v1beta1/jwt.proto
  security/v1beta1/request_authentication.gen.json
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: size/XS, release-notes-none

#2234 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2237 [release-1.13] add otel ALS provider
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  python/istio_api/mesh/v1alpha1/config_pb2.py
  releasenotes/notes/open-telemetry-provider.yaml
Labels: size/M, release-notes-none

#2232 Updating LB enum to allow switch in default
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/destination_rule_json.gen.go
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/destination_rule_deepcopy.gen.go
  networking/v1beta1/destination_rule_json.gen.go
  proto.lock
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
  releaselocks/release-1.0/proto.lock.status
  releaselocks/release-1.1/proto.lock.status
  releaselocks/release-1.2/proto.lock.status
  releaselocks/release-1.3/proto.lock.status
  releaselocks/release-1.4/proto.lock.status
  releaselocks/release-1.5/proto.lock.status
  releaselocks/release-1.6/proto.lock.status
  releasenotes/notes/lb-algorithm-enum-change.yaml
Labels: size/L

#2227 WasmPlugin add VmConfig
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  extensions/v1alpha1/wasm_deepcopy.gen.go
  extensions/v1alpha1/wasm_json.gen.go
  kubernetes/customresourcedefinitions.gen.yaml
  python/istio_api/extensions/v1alpha1/wasm_pb2.py
Labels: size/M, release-notes-none

#2242 fix fuzz
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  python/istio_api/extensions/v1alpha1/wasm_pb2.py
Labels: size/XS, release-notes-none

#2243 Automator: update common-files@release-1.13 in istio/api@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2246 [release-1.13] lint updates needed for common-files updates
  go.mod
  operator/fixup_structs/main.go
Labels: size/S, release-notes-none

#2245 Automator: update common-files@release-1.13 in istio/api@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2153 add warmup duration secs api
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  python/istio_api/networking/v1alpha3/destination_rule_pb2.py
  python/istio_api/networking/v1beta1/destination_rule_pb2.py
  releasenotes/notes/slow-start.yaml
Labels: cla: yes, size/S

#2248 Automator: update common-files@release-1.13 in istio/api@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2250 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2241 Add HeadersToDownstreamOnAllow to ext_authz
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  python/istio_api/mesh/v1alpha1/config_pb2.py
Labels: size/XL, release-notes-none

#2253 update envoyfilter EXTENSION_CONFIG demo
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_json.gen.go
Labels: size/S, release-notes-none, cherrypick/release-1.13

#2255 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2256 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#2258 Automator: update common-files@release-1.12 in istio/api@release-1.12
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#2259 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
