Repository istio/api, pull requests merged in 2022-10, with the labels that each got.

#2491 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2492 Automator: update common-files@release-1.14 in istio/api@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2493 Automator: update common-files@release-1.15 in istio/api@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2494 Automator: update common-files@master in istio/api@master
  LICENSE
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2495 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2497 [release-1.15] telemetry: update doc link
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: size/XS, release-notes-none

#2505 [release-1.15] telemetry: fix required field
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: size/XS, release-notes-none

#2506 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2507 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2508 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2511 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2513 [release-1.16] Added note tls version below 1.2 should set compatible cipher suites
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
Labels: size/S, release-notes-none

#2517 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#2518 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2519 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2521 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2523 Automator: update common-files@master in istio/api@master
  analysis/v1alpha1/message_deepcopy.gen.go
  authentication/v1alpha1/policy_deepcopy.gen.go
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  extensions/v1alpha1/wasm_deepcopy.gen.go
  meta/v1alpha1/status_deepcopy.gen.go
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/envoy_filter_deepcopy.gen.go
  networking/v1alpha3/gateway_deepcopy.gen.go
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/virtual_service_deepcopy.gen.go
  networking/v1alpha3/workload_entry_deepcopy.gen.go
  networking/v1alpha3/workload_group_deepcopy.gen.go
  networking/v1beta1/destination_rule_deepcopy.gen.go
  networking/v1beta1/gateway_deepcopy.gen.go
  networking/v1beta1/proxy_config_deepcopy.gen.go
  networking/v1beta1/service_entry_deepcopy.gen.go
  networking/v1beta1/sidecar_deepcopy.gen.go
  networking/v1beta1/virtual_service_deepcopy.gen.go
  networking/v1beta1/workload_entry_deepcopy.gen.go
  networking/v1beta1/workload_group_deepcopy.gen.go
  security/v1alpha1/ca_deepcopy.gen.go
  security/v1beta1/authorization_policy_deepcopy.gen.go
  security/v1beta1/jwt_deepcopy.gen.go
  security/v1beta1/peer_authentication_deepcopy.gen.go
  security/v1beta1/request_authentication_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  type/v1beta1/selector_deepcopy.gen.go
Labels: size/XS, auto-merge, release-notes-none

#2524 Update dependencies
  go.mod
  go.sum
Labels: size/L, release-notes-none

#2525 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2520 Update tls des
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
Labels: size/XS, release-notes-none, cherrypick/release-1.16

#2529 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2531 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2514 Added listener filter patching
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: size/M, release-notes-none

#2532 remove thrift config from config
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: release-notes-none

#2515 hpa: Policies move to v2beta2
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
Labels: area/environments, size/L, release-notes-none
