Repository istio/api, pull requests merged in 2022-01, with the labels that each got.

#2198 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#2200 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2201 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2199 fix httpbin.com -> example.com
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  networking/v1beta1/service_entry_deepcopy.gen.go
  networking/v1beta1/service_entry_json.gen.go
Labels: ok-to-test, size/M, release-notes-none

#2203 fix storageversion for workload group
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1beta1/workload_group.pb.go
  networking/v1beta1/workload_group.proto
  releasenotes/notes/workloadgroup-v1beta1.yaml
Labels: size/XS

#2204 use default Telemetry accessLogging provider "envoy" instead of "envo…
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  telemetry/v1alpha1/telemetry_deepcopy.gen.go
  telemetry/v1alpha1/telemetry_json.gen.go
Labels: ok-to-test, size/XS

#2206 pickup SD extension configuration changes from `istio/proxy`
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.proto
Labels: size/S, release-notes-none

#2165 added tls to sidecar api
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/sidecar_deepcopy.gen.go
  networking/v1alpha3/sidecar_json.gen.go
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
  python/istio_api/networking/v1alpha3/sidecar_pb2.py
  python/istio_api/networking/v1beta1/sidecar_pb2.py
  releasenotes/notes/hybrid_sidecar_mode.yaml
Labels: cla: yes, ok-to-test, size/L

#2208 fix retryOn doc
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: size/XS, release-notes-none

#2174 proxyconfig(service-cluster): add control for service cluster naming
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  releasenotes/notes/2174.yaml
Labels: cla: yes, size/M

#2209 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2211 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2213 Revert 1.13
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/config_pb2.py
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  releasenotes/notes/2174.yaml
  releasenotes/notes/open-telemetry-provider.yaml
Labels: size/L

#2215 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2214 [release-1.13] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#2210 [release-1.12] fix retryOn doc
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: size/XS, release-notes-none

#2218 Automator: update common-files@release-1.13 in istio/api@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2219 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#2217 Move more examples to `credentialName`
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
Labels: size/S, release-notes-none

#2221 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2223 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2225 Automator: update common-files@release-1.11 in istio/api@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2222 [release-1.13] proxyconfig(service-cluster): add control for service cluster naming
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  python/istio_api/mesh/v1alpha1/proxy_pb2.py
  releasenotes/notes/2174.yaml
Labels: size/M, auto-merge, release-notes-none

#2226 lint updates needed for common-files updates
  go.mod
  operator/fixup_structs/main.go
Labels: size/S, release-notes-none

#2224 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2228 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
