Repository istio/api, pull requests merged in 2023-08, with the labels that each got.

#2805 virtual service supports traffic mirroring to multiple destinations
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/virtual_service_deepcopy.gen.go
  networking/v1alpha3/virtual_service_json.gen.go
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
  networking/v1beta1/virtual_service_deepcopy.gen.go
  networking/v1beta1/virtual_service_json.gen.go
  proto.lock
Labels: size/L, release-notes-none

#2876 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2875 Drop json schema generation
  analysis/v1alpha1/message.gen.json
  authentication/v1alpha1/istio.authentication.v1alpha1.gen.json
  cue.yaml
  extensions/v1alpha1/wasm.gen.json
  gen.sh
  mcp/v1alpha1/istio.mcp.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  meta/v1alpha1/status.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/envoy_filter.gen.json
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/sidecar.gen.json
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/workload_entry.gen.json
  networking/v1alpha3/workload_group.gen.json
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/proxy_config.gen.json
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/sidecar.gen.json
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/workload_entry.gen.json
  networking/v1beta1/workload_group.gen.json
  security/v1alpha1/ca.gen.json
  security/v1beta1/authorization_policy.gen.json
  security/v1beta1/jwt.gen.json
  security/v1beta1/peer_authentication.gen.json
  security/v1beta1/request_authentication.gen.json
  type/v1beta1/selector.gen.json
Labels: size/M, release-notes-none

#2877 Automator: update common-files@release-1.18 in istio/api@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2880 [release-1.19] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#2881 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2882 Discourage unsafe ProtocolDetectionTimeout in mesh config
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: size/XS, release-notes-none

#2883 Automator: update common-files@release-1.19 in istio/api@release-1.19
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2886 Automator: update common-files@release-1.19 in istio/api@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2887 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2890 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2891 Automator: update common-files@release-1.19 in istio/api@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2896 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2894 Fix AuthorizationPolicy typo
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: size/XS, release-notes-none, cherrypick/release-1.19

#2898 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2899 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2240 Add controls around injected headers
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
Labels: kind/enhancement, size/L, lifecycle/automatically-closed, release-notes-none

#2906 Update dependencies
  go.mod
  go.sum
  licenses/google.golang.org/genproto/googleapis/api/LICENSE
  licenses/google.golang.org/genproto/googleapis/rpc/LICENSE
Labels: size/L, release-notes-none

#2908 Automator: update common-files@release-1.19 in istio/api@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2902 [release-1.19] Add controls around injected headers
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
Labels: size/L, release-notes-none

#2904 add support for network wasm filters
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  proto.lock
Labels: size/M, release-notes-none

#2909 Fix typo Authorizaion to Authorization
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
Labels: ok-to-test, size/XS, release-notes-none, cherrypick/release-1.19

#2911 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2914 [release-1.19] Fix typo Authorizaion to Authorization
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
Labels: size/XS, release-notes-none

#2913 add a note about the default inbound interception mode
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: ok-to-test, size/XS, release-notes-none

#2916 update proto for WorkloadEntry since address is no longer required
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  proto.lock
Labels: size/L, release-notes-none

#2910 add metadata headers for proxyHeaders API
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  proto.lock
Labels: size/M, release-notes-none

#2917 [release-1.19] update proto for WorkloadEntry since address is no longer required
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/workload_entry.gen.json
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_entry.proto
  networking/v1alpha3/workload_group.gen.json
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/workload_entry.gen.json
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_entry.proto
  networking/v1beta1/workload_group.gen.json
  proto.lock
Labels: size/L, auto-merge, release-notes-none

#2918 fix JWT claim based routing doc
  security/v1/request_authentication.pb.go
  security/v1/request_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: size/S, release-notes-none, cherrypick/release-1.19

#2921 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2919 Update virtualservice HTTPRetry docs for the `attempt` field
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: ok-to-test, size/XS, release-notes-none

#2922 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2923 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
