Repository istio/api, pull requests merged in 2023-06, with the labels that each got.

#2799 wasm: add fail_open for telemetry plugins
  extensions/v1alpha1/wasm.gen.json
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  proto.lock
Labels: size/M, release-notes-none

#2802 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2803 docs changes for ocsp staple support
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/sidecar.gen.json
Labels: size/S, release-notes-none

#2800 stats: allow custom histogram buckets
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/S, release-notes-none

#2806 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2807 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2809 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2810 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2808 [release-1.18] docs changes for crl support
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.gen.json
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/sidecar.gen.json
Labels: size/S, release-notes-none

#2813 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2814 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2815 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2816 clarify the documentation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/XS, release-notes-none

#2821 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2822 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2823 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2761 Add authz dry-run example
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.pb.html
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: size/M, release-notes-none

#2824 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2826 Automator: update common-files@release-1.18 in istio/api@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2827 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2828 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2829 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2811 fixes for Duplicate reference docs overwriting each other
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.pb.html
  networking/v1alpha3/workload_group.proto
  networking/v1beta1/workload_group.pb.go
  networking/v1beta1/workload_group.pb.html
  networking/v1beta1/workload_group.proto
  scripts/sync.sh
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.pb.html
  security/v1/authorization_policy.proto
  security/v1/jwt.pb.go
  security/v1/jwt.pb.html
  security/v1/jwt.proto
  security/v1/request_authentication.pb.go
  security/v1/request_authentication.pb.html
  security/v1/request_authentication.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
Labels: size/XL, release-notes-none

#2831 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2833 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2834 envoyfilter: fix wrong doc
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: size/XS, release-notes-none, cherrypick/release-1.17, cherrypick/release-1.18

#2825 [release-1.18] Add authz dry-run example
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.pb.html
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: size/M, auto-merge, release-notes-none

#2838 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2836 [release-1.18] envoyfilter: fix wrong doc
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: size/XS, release-notes-none

#2839 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2840 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2841 Automator: update common-files@release-1.18 in istio/api@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2842 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2843 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2835 [release-1.17] envoyfilter: fix wrong doc
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: size/XS, release-notes-none

#2844 Wrong defaults for Destination Rule
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
  releasenotes/notes/destination-rule-default-values.yaml
Labels: ok-to-test, size/S
