Repository istio/api, pull requests merged in 2023-02, with the labels that each got.

#2664 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2665 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2666 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2668 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2670 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2671 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#2672 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2675 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2676 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2677 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2678 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2679 Automator: update common-files@release-1.15 in istio/api@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2681 Fix link
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.pb.html
  security/v1/authorization_policy.proto
Labels: size/XS, release-notes-none

#2682 Add ztunnel component to operator API
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
Labels: size/XS, release-notes-none

#2683 Fix link
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: size/S, release-notes-none

#2680 telemetry: allow disable 128bit trace id for zipkin provider
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
Labels: size/S, release-notes-none

#2543 Add ecdh_curves support
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  releasenotes/notes/ecdh_support.yaml
Labels: size/M

#2684 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2686 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2688 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2687 replace quotes with backticks when referring to values
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.pb.html
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: size/M, release-notes-none

#2689 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2690 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2691 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#2692 Clarify credentialName usage in ClientTLSSettings for separate ca secret
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: size/XS, release-notes-none

#2659 VirtualService docs minor formatting fixes
  networking/v1alpha3/virtual_service.gen.json
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.gen.json
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: ok-to-test, size/XS, release-notes-none
