Repository istio/api, pull requests merged in 2023-01, with the labels that each got.

#2611 [release-1.16] Add OpenTelemetry Tracing Provider to Docs
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: size/XS, release-notes-none

#2612 clarify warmup duration docs in destination rule
  networking/v1alpha3/destination_rule.gen.json
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.gen.json
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: release-notes-none

#2615 Clarify that Sidecar is not applicable to gateways
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/sidecar.proto
Labels: size/XS, release-notes-none

#2617 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2618 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2622 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2623 fix CVE-2022-41717 vulnerability
  go.mod
  go.sum
Labels: ok-to-test, size/S, release-notes-none

#2625 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2627 Add `appProtocol` field to operator/v1alpha1 ServicePort
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
Labels: ok-to-test, size/XS

#2628 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2629 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#2630 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2626 Separate ServiceEntry port from Gateway Server and Sidecar ingress listener
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.gen.json
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1alpha3/sidecar.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/service_entry.gen.json
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/service_entry.proto
  networking/v1beta1/service_entry_deepcopy.gen.go
  networking/v1beta1/service_entry_json.gen.go
  networking/v1beta1/sidecar.gen.json
  proto.lock
Labels: size/L, release-notes-none

#2631 Automator: update common-files@release-1.15 in istio/api@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2632 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2636 fix depguard
  operator/v1alpha1/operator_json.go
Labels: size/S, release-notes-none

#2634 Deprecate Port.TargetPort
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/sidecar.gen.json
  proto.lock
Labels: size/M, release-notes-none

#2637 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2638 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2639 [release-1.17] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#2640 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2641 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2643 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2644 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2646 Clarify protocol description for Gateway port
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/sidecar.gen.json
Labels: size/XS, release-notes-none

#2648 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2647 [release-1.17] Clarify protocol description for Gateway port
  networking/v1alpha3/gateway.gen.json
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/sidecar.gen.json
  networking/v1beta1/gateway.gen.json
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/gateway.proto
  networking/v1beta1/sidecar.gen.json
Labels: size/XS, release-notes-none

#2649 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2650 Automator: update common-files@release-1.15 in istio/api@release-1.15
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#2651 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2652 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#2653 Automator: update common-files@release-1.17 in istio/api@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2654 Automator: update common-files@release-1.16 in istio/api@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2655 Automator: update common-files@release-1.15 in istio/api@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2656 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2657 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2658 small fix in authz docs
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.pb.html
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: size/XS

#2662 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2635 mark Lightstep provider deprecated
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  releasenotes/notes/2635.yaml
Labels: size/S, cherrypick/release-1.17

#2663 [release-1.17] mark Lightstep provider deprecated
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.gen.json
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  releasenotes/notes/2635.yaml
Labels: size/S, release-notes-none
