Repository istio/api, pull requests merged in 2024-10, with the labels that each got.

#3307 Codify labels and annotations that have been added directly to istio/istio
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
Labels: size/L, release-notes-none

#3302 Add CEL validation to SE and WG
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1/service_entry_alias.gen.go
  networking/v1/workload_group_alias.gen.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.pb.html
  networking/v1alpha3/workload_group.proto
  networking/v1beta1/service_entry_alias.gen.go
  networking/v1beta1/workload_group_alias.gen.go
  tests/testdata/serviceentry-invalid.yaml
  tests/testdata/serviceentry-valid.yaml
  tests/testdata/workloadgroup-invalid.yaml
  tests/testdata/workloadgroup-valid.yaml
Labels: size/L, release-notes-none

#3321 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3324 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  kubernetes/customresourcedefinitions.gen.yaml
Labels: size/XS, auto-merge, release-notes-none

#3325 move cert and chain fields to boolean
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: release-notes-none

#3326 Automator: update common-files@release-1.23 in istio/api@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3216 feat(DestinationRules): Adding aggression and min_weight_percent to DestinationRules API
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1/destination_rule_alias.gen.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/destination_rule_json.gen.go
  networking/v1beta1/destination_rule_alias.gen.go
  releasenotes/notes/slow-start-aggression-minimum-percent-parameters.yaml
  tests/testdata/destinationrule-invalid.yaml
  tests/testdata/destinationrule-valid.yaml
Labels: ok-to-test, size/L

#3327 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3330 [WIP] Run make-gen for protoc-gen-go v1.35.1
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/proxy_config.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/XS, release-notes-none

#3320 Fix over-correcting new SE CEL validation
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1/service_entry_alias.gen.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1beta1/service_entry_alias.gen.go
  tests/testdata/serviceentry-valid.yaml
Labels: size/S, release-notes-none

#3331 Clarify filemounted crl usage
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
Labels: size/XS, release-notes-none

#3332 annotations: remove obsolete entries
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/M, release-notes-none

#3334 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3336 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3337 Run make gen
  security/v1alpha1/ca_grpc.pb.go
Labels: size/XS, release-notes-none

#3329 annotations: create an annotation for native sidecars
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  releasenotes/notes/native-sidecar-annotation.yaml
Labels: ok-to-test, size/S

#3328 Add traffic distribution annotation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/S, release-notes-none

#3338 Add ingress bypass annotation to the API
  annotation/annotations.gen.go
  annotation/annotations.yaml
Labels: size/S, release-notes-none

#3342 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#3339 Add clear_route_cache parameter to ExtAuthZ extensions
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: ok-to-test, size/S, release-notes-none

#3319 Improve documentation for subjectAltNames
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
Labels: ok-to-test, size/S, release-notes-none

#3335 Add ObservedGeneration field to IstioCondition
  kubernetes/customresourcedefinitions.gen.yaml
  meta/v1alpha1/status.pb.go
  meta/v1alpha1/status.pb.html
  meta/v1alpha1/status.proto
  releasenotes/notes/53331.yaml
Labels: ok-to-test, size/S

#3343 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3346 [release-1.24] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#3347 Automator: update common-files@release-1.24 in istio/api@release-1.24
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
