Repository istio/api, pull requests merged in 2024-11, with the labels that each got.

#3348 Automator: update common-files@release-1.24 in istio/api@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3349 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3351 Clarify that while this annotation has been deprecated, the label of the same name is still available.
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: ok-to-test, size/XS, release-notes-none

#3356 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3357 add missing slash to fix docs path/lint
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: size/XS, release-notes-none, cherrypick/release-1.24

#3355 Remove enableCoreDump annotation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/XS, release-notes-none

#3359 fix quote
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: size/XS, release-notes-none

#3360 noticed typo in labels gen proto link in description note
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
Labels: size/XS, release-notes-none

#3364 Fix incorrect SE docs
  networking/v1/service_entry_alias.gen.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1beta1/service_entry_alias.gen.go
Labels: size/XS, release-notes-none

#3365 [release-1.24] Update reference docs for ambient GA
  analysis/v1alpha1/message.pb.html
  extensions/v1alpha1/wasm.pb.html
  label/labels.gen.go
  label/labels.pb.html
  label/labels.yaml
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  meta/v1alpha1/status.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_group.pb.html
  networking/v1beta1/proxy_config.pb.html
  security/v1alpha1/ca.pb.html
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/request_authentication.pb.html
  telemetry/v1alpha1/telemetry.pb.html
  type/v1beta1/selector.pb.html
Labels: size/XS, release-notes-none

#3358 [release-1.24] add missing slash to fix docs path/lint
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: size/XS, release-notes-none

#3367 hide tracer provider
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: size/XS, release-notes-none

#3362 Add ambient virtual interface annotation for pods
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
  releasenotes/notes/3362.yaml
Labels: size/S

#3369 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3368 Run make gen with latest image
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/proxy_config.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/XS, release-notes-none
