Repository istio/api, pull requests merged in 2024-08, with the labels that each got.

#3289 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3290 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3291 Automator: update common-files@release-1.22 in istio/api@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3292 Automator: update common-files@release-1.23 in istio/api@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3287 Remove obsolete releaselocks
  releaselocks/release-1.5/proto.lock.status
  releaselocks/release-1.6/proto.lock.status
Labels: size/XXL, release-notes-none

#3293 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3294 Fix minor typo
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
Labels: size/XS, release-notes-none

#3296 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3297 Automator: update common-files@release-1.23 in istio/api@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3295 Pick up changes to CRD template naming and fix excessive WG validation
  kubernetes/customresourcedefinitions.gen.yaml
  meta/v1alpha1/status.pb.go
  meta/v1alpha1/status.proto
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.proto
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
  type/v1beta1/selector.pb.go
  type/v1beta1/selector.proto
Labels: size/S, release-notes-none

#3298 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#3299 1.23: fix workload group regression
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.proto
Labels: size/XS, release-notes-none

#3300 Docs: Change snake_case to camelCase
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: ok-to-test, size/M, release-notes-none

#3301 support grpc configuration for opentelemetry extension provider
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: kind/enhancement, ok-to-test, size/M, release-notes-none

#3303 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
