Repository istio/api, pull requests merged in 2024-01, with the labels that each got.

#3032 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3031 align `selector` comments of PeerAuthentication with `RequestAuthentication` and `AuthorizationPolicy`
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
Labels: ok-to-test, size/XS, release-notes-none

#3033 docs: use Kubernetes instead of k8s in the proto field comments
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
Labels: size/M, release-notes-none

#3035 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3036 docs: fix rendering of links and code snippets
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
Labels: size/M, release-notes-none

#3038 agent: remove BDS
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  releasenotes/notes/bds-removal.yaml
Labels: size/M

#3039 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3040 Automator: update common-files@release-1.19 in istio/api@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3041 Automator: update common-files@release-1.20 in istio/api@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3042 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3043 update annotations and labels page
  annotation/annotations.pb.html
  label/labels.pb.html
Labels: size/XS, release-notes-none

#3046 Add compatibilityVersion to IstioOperator
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
Labels: size/S, release-notes-none

#3047 Automator: update common-files@release-1.20 in istio/api@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3048 update annotations and labels page
  annotation/annotations.pb.html
  label/labels.pb.html
Labels: size/XS, release-notes-none

#3050 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3051 Run make gen with new protoc
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  go.mod
  go.sum
  mcp/v1alpha1/mcp.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/gateway.pb.go
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/service_entry.pb.go
  networking/v1beta1/sidecar.pb.go
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/workload_entry.pb.go
  networking/v1beta1/workload_group.pb.go
  operator/v1alpha1/operator.pb.go
  proto.lock
  security/v1/authorization_policy.pb.go
  security/v1/jwt.pb.go
  security/v1/request_authentication.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/jwt.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/XL, release-notes-none

#3055 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#3057 docs: field name and minor formatting fixes
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: release-notes-none

#3058 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3060 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3059 Add docs for max_concurrent_streams
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1beta1/destination_rule.pb.go
  networking/v1beta1/destination_rule.proto
Labels: size/XS, release-notes-none

#3061 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3063 [release-1.21] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#3064 Automator: update common-files@release-1.21 in istio/api@release-1.21
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3065 docs: fix formatting issues, typo, add links
  kubernetes/customresourcedefinitions.gen.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: size/M, release-notes-none

#2798 Remove defaultRevision
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
Labels: ok-to-test, size/S

#3066 [release-1.21] Remove defaultRevision
  operator/v1alpha1/istio.operator.v1alpha1.pb.html
  operator/v1alpha1/operator.pb.go
  operator/v1alpha1/operator.proto
  proto.lock
Labels: size/S, release-notes-none

#3067 [release-1.21] docs: fix formatting issues, typo, add links
  kubernetes/customresourcedefinitions.gen.yaml
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: size/M, release-notes-none

#3068 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2998 OpenTelemetryTracingProvider : New configurations to export via HTTP
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
  releasenotes/notes/otel-tracing-provider-http-exporter.yaml
Labels: ok-to-test, size/L

#3070 docs: formatting fixes in WasmPlugin
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
Labels: release-notes-none

#3069 add shortname for authz
  kubernetes/customresourcedefinitions.gen.yaml
  releasenotes/notes/authz-shortname.yaml
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.proto
Labels: size/S

#3071 [release-1.21] docs: formatting fixes in WasmPlugin
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
Labels: size/M, release-notes-none

#3072 Add missing deprecated tag for mesh fields
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  proto.lock
Labels: ok-to-test, size/S, release-notes-none, cherrypick/release-1.21

#3074 Update SUPPORT.md
  SUPPORT.md
Labels: size/XS, release-notes-none

#3073 Fix broken doc link to XDS description
  mcp/Readme.md
Labels: size/XS, release-notes-none

#3075 docs: add notes for ports used in AuthPolicy/PeerAuth
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
Labels: release-notes-none

#3076 Automator: update common-files@master in istio/api@master
  .gitattributes
  SUPPORT.md
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
