Repository istio/api, pull requests merged in 2024-04, with the labels that each got.

#3144 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#3146 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/M, auto-merge, release-notes-none

#3148 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3149 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#3150 Automator: update common-files@release-1.21 in istio/api@release-1.21
  .devcontainer/devcontainer.json
  annotation/annotations.pb.html
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  label/labels.pb.html
Labels: size/XS, auto-merge, release-notes-none

#3151 Automator: update common-files@release-1.20 in istio/api@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3152 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/M, auto-merge, release-notes-none

#3143 add new phase to WasmPlugin
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
Labels: size/XS

#3153 Automator: update common-files@release-1.19 in istio/api@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3156 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#3157 Revert "add new phase to WasmPlugin"
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
Labels: size/XS, release-notes-none

#3158 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3160 EnvoyFilter: implement `targetRefs`
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: size/S, release-notes-none

#3159 policy attachment: allow `targetRefs`
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
  security/v1/request_authentication.pb.go
  security/v1/request_authentication.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  telemetry/v1/telemetry.pb.go
  telemetry/v1/telemetry.proto
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: size/L, release-notes-none

#3161 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3163 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3162 Add docs and examples for path templating
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1/authorization_policy.pb.go
  security/v1/authorization_policy.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
Labels: size/S, release-notes-none

#3166 [release-1.22] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#3135 [API] Implement Release channels
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  releasenotes/notes/release-channels.yaml
Labels: size/S

#3170 Automator: update common-files@release-1.22 in istio/api@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3172 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3174 Add extended release channel flag to ProxyConfig
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.proto
Labels: size/XS, release-notes-none
