Repository istio/api, pull requests merged in 2024-12, with the labels that each got.

#3373 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3350 Add StatefulFormatter to mesh.ProxyConfig
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  networking/v1beta1/proxy_config.proto
  releasenotes/notes/preserve-header-case.yaml
Labels: size/S

#3375 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#3372 Support grpc probes for workload group health checks
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1/workload_group_alias.gen.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1alpha3/workload_group.pb.html
  networking/v1alpha3/workload_group.proto
  networking/v1alpha3/workload_group_deepcopy.gen.go
  networking/v1alpha3/workload_group_json.gen.go
  networking/v1beta1/workload_group_alias.gen.go
  releasenotes/notes/add-workload-group-grpc-probe.yaml
Labels: size/S

#3377 Automator: update common-files@release-1.24 in istio/api@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3378 Automator: update common-files@release-1.22 in istio/api@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3379 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#3380 Automator: update common-files@release-1.24 in istio/api@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3381 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3382 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#3371 doc: Adds explanation of the '~' character to networking.istio.io/exportTo annotation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: ok-to-test, size/XS, release-notes-none

#3383 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3384 Fix some proto descriptions
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  networking/v1/destination_rule_alias.gen.go
  networking/v1/service_entry_alias.gen.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/destination_rule_alias.gen.go
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.pb.html
  networking/v1beta1/proxy_config.proto
  networking/v1beta1/service_entry_alias.gen.go
  security/v1/peer_authentication_alias.gen.go
  security/v1/request_authentication_alias.gen.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: size/L, release-notes-none

#3386 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3387 Automator: update common-files@release-1.24 in istio/api@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3385 [release-1.24] Fix some proto descriptions
  analysis/v1alpha1/message.pb.html
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  meta/v1alpha1/status.pb.html
  networking/v1/destination_rule_alias.gen.go
  networking/v1/service_entry_alias.gen.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_group.pb.html
  networking/v1beta1/destination_rule_alias.gen.go
  networking/v1beta1/proxy_config.pb.go
  networking/v1beta1/proxy_config.pb.html
  networking/v1beta1/proxy_config.proto
  networking/v1beta1/service_entry_alias.gen.go
  security/v1/peer_authentication_alias.gen.go
  security/v1/request_authentication_alias.gen.go
  security/v1alpha1/ca.pb.html
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  type/v1beta1/selector.pb.html
Labels: size/L, auto-merge, release-notes-none

#3388 Generate new format docs
  analysis/v1alpha1/message.pb.html
  extensions/v1alpha1/wasm.pb.html
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  meta/v1alpha1/status.pb.html
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/workload_entry.pb.html
  networking/v1alpha3/workload_group.pb.html
  networking/v1beta1/proxy_config.pb.html
  security/v1alpha1/ca.pb.html
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/request_authentication.pb.html
  telemetry/v1alpha1/telemetry.pb.html
  type/v1beta1/selector.pb.html
Labels: size/XS, release-notes-none

#3391 manual cherrypick of #3359
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: size/XS, release-notes-none

#3393 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3392 update dependencies
  go.mod
  go.sum
  licenses/golang.org/x/net/LICENSE
  licenses/golang.org/x/sys/LICENSE
  licenses/golang.org/x/text/LICENSE
Labels: size/M, release-notes-none

#3394 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3396 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3340 AuthorizationPolicy: add `serviceAccounts` field
  kubernetes/customresourcedefinitions.gen.yaml
  security/v1/authorization_policy_alias.gen.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  tests/testdata/authz-invalid.yaml
  tests/testdata/authz-valid.yaml
Labels: size/L, release-notes-none

#3345 Add JSON marshaling for non-CRD types
  buf.gen-noncrd.yaml
  mcp/v1alpha1/metadata_json.gen.go
  mcp/v1alpha1/resource_json.gen.go
  mesh/v1alpha1/config_json.gen.go
  mesh/v1alpha1/network_json.gen.go
  mesh/v1alpha1/proxy_json.gen.go
Labels: size/XS, release-notes-none

#3398 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
