Repository istio/api, pull requests merged in 2024-07, with the labels that each got.

#3184 Update PeerAuthentication docs
  security/v1/peer_authentication_alias.gen.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
Labels: size/S, release-notes-none, cherrypick/release-1.22

#3205 [release-1.22] virtual service: minor grammar fix
  networking/v1/virtual_service.pb.go
  networking/v1/virtual_service.proto
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
  networking/v1beta1/virtual_service.pb.go
  networking/v1beta1/virtual_service.proto
Labels: size/XS, lifecycle/staleproof, auto-merge, release-notes-none

#3206 [release-1.22] proxy config: clarify concurrency docs
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: size/XS, lifecycle/staleproof, auto-merge, release-notes-none

#3247 Improve VS retry documentation
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: size/S, release-notes-none, cherrypick/release-1.22

#3252 manual cherry-pick of #3184
  security/v1/peer_authentication.pb.go
  security/v1/peer_authentication.proto
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.pb.html
  security/v1beta1/peer_authentication.proto
Labels: size/S, release-notes-none

#3253 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3254 Automator: update common-files@release-1.21 in istio/api@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3255 Automator: update common-files@release-1.22 in istio/api@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3256 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3244 New Status proto for ServiceEntry
  networking/v1alpha3/serviceentry-status.pb.go
  networking/v1alpha3/serviceentry-status.pb.html
  networking/v1alpha3/serviceentry-status.proto
  networking/v1alpha3/serviceentry-status_deepcopy.gen.go
  networking/v1alpha3/serviceentry-status_json.gen.go
Labels: size/M, release-notes-none

#3257 minor reorg and fixes
  meta/v1alpha1/status.pb.go
  meta/v1alpha1/status.pb.html
  meta/v1alpha1/status.proto
  networking/v1/service_entry_alias.gen.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/service_entry_deepcopy.gen.go
  networking/v1alpha3/service_entry_json.gen.go
  networking/v1alpha3/serviceentry-status.pb.go
  networking/v1alpha3/serviceentry-status.pb.html
  networking/v1alpha3/serviceentry-status.proto
  networking/v1alpha3/serviceentry-status_deepcopy.gen.go
  networking/v1alpha3/serviceentry-status_json.gen.go
  networking/v1beta1/service_entry_alias.gen.go
Labels: size/L, release-notes-none

#3261 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3263 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3235 validation: add CEL validation to workload entry
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1/workload_entry_alias.gen.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/workload_entry_alias.gen.go
  tests/testdata/workloadentry-invalid.yaml
  tests/testdata/workloadentry-valid.yaml
Labels: size/L, release-notes-none

#3260 Make TTL allow duration=0s again
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
Labels: size/XS, release-notes-none

#3266 [release-1.23] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#3269 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3272 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  kubernetes/customresourcedefinitions.gen.yaml
Labels: size/XS, auto-merge, release-notes-none

#3276 add new pattern SERVICE_NAME variable for stat prefix
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: ok-to-test, size/XS, release-notes-none

#3271 Allow targetRef to SE
  kubernetes/customresourcedefinitions.gen.yaml
  type/v1beta1/selector.pb.go
  type/v1beta1/selector.proto
Labels: size/XS, release-notes-none

#3277 Automator: update common-files@master in istio/api@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3279 fix: ServiceEntryStatus
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  releasenotes/notes/3279.yaml
Labels: size/XS, cherrypick/release-1.23

#3273 Make observedGeneration intOrStr
  kubernetes/customresourcedefinitions.gen.yaml
  meta/v1alpha1/status.pb.go
  meta/v1alpha1/status.proto
Labels: size/XS, release-notes-none

#3270 Improve OutboundTrafficPolicy docs
  kubernetes/customresourcedefinitions.gen.yaml
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  networking/v1/sidecar_alias.gen.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/sidecar.pb.html
  networking/v1alpha3/sidecar.proto
  networking/v1beta1/sidecar_alias.gen.go
Labels: size/M, release-notes-none

#3274 docs: clarify target ref to service
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
Labels: size/XS, release-notes-none

#3281 [release-1.23] fix: ServiceEntryStatus
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
  releasenotes/notes/3279.yaml
Labels: size/XS, release-notes-none

#3282 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3283 Regen after intorstr changes
  kubernetes/customresourcedefinitions.gen.yaml
Labels: size/XS, release-notes-none

#3284 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
