Repository istio/api, pull requests merged in 2025-06, with the labels that each got.

#3510 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3511 fix doc for preserveHttp1HeaderCase
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: size/XS, release-notes-none

#3513 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3516 update sourceLabels and sourceNamespace docs
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: size/S, release-notes-none

#3519 [release-1.26] update sourceLabels and sourceNamespace docs
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: size/S, release-notes-none

#3520 [release-1.26] fix doc for preserveHttp1HeaderCase
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
Labels: size/XS, release-notes-none

#3522 format protobuf files
  analysis/v1alpha1/message.proto
  envoy/config/filter/http/jwt_auth/v2alpha1/config.proto
  envoy/config/filter/network/metadata_exchange/metadata_exchange.proto
  envoy/extensions/stackdriver/config/v1alpha1/config.proto
  envoy/extensions/stats/config.proto
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.proto
  gen.sh
  mcp/v1alpha1/metadata.proto
  mcp/v1alpha1/resource.proto
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/network.proto
  mesh/v1alpha1/proxy.proto
  meta/v1alpha1/status.proto
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/gateway.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/sidecar.proto
  networking/v1alpha3/virtual_service.proto
  networking/v1alpha3/workload_entry.proto
  networking/v1alpha3/workload_group.proto
  networking/v1beta1/proxy_config.proto
  security/v1alpha1/ca.proto
  security/v1beta1/authorization_policy.proto
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
  stability/level.proto
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.proto
  type/v1beta1/selector.proto
Labels: size/XL, release-notes-none

#3524 Automator: update common-files@release-1.24 in istio/api@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3525 Automator: update common-files@release-1.25 in istio/api@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3527 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3528 Automator: update common-files@release-1.26 in istio/api@release-1.26
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3530 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
