Repository istio/api, pull requests merged in 2025-07, with the labels that each got.

#3537 Automator: update common-files@release-1.26 in istio/api@release-1.26
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3538 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3542 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3532 add x-forwarded-host and x-forwarded-port in proxy headers
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/proxy.pb.go
  mesh/v1alpha1/proxy.proto
  mesh/v1alpha1/proxy_json.gen.go
Labels: size/S, release-notes-none

#3543 unhide ambient.istio.io/bypass-inbound-capture annotation
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: ok-to-test, size/XS, release-notes-none

#3544 feat: add tls.caCertCredentialName
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/gateway.pb.html
  networking/v1alpha3/gateway.proto
  releasenotes/notes/3544.yaml
Labels: ok-to-test, size/S
