Repository istio/api, pull requests merged in 2025-01, with the labels that each got.

#3333 Validation: add documentation and use CEL pre-processor
  GUIDELINES.md
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1/destination_rule_alias.gen.go
  networking/v1/service_entry_alias.gen.go
  networking/v1/workload_entry_alias.gen.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.proto
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.proto
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_entry.proto
  networking/v1beta1/destination_rule_alias.gen.go
  networking/v1beta1/service_entry_alias.gen.go
  networking/v1beta1/workload_entry_alias.gen.go
  security/v1/authorization_policy_alias.gen.go
  security/v1/peer_authentication_alias.gen.go
  security/v1/request_authentication_alias.gen.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.proto
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
  telemetry/v1/telemetry_alias.gen.go
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.proto
Labels: size/L, release-notes-none

#3399 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3402 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3403 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3405 Automator: update common-files@master in istio/api@master
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  common/.commonfiles.sha
  common/config/license-lint.yml
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/proxy_config.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/XS, auto-merge, release-notes-none

#3407 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#3408 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3409 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3410 Automator: update common-files@release-1.24 in istio/api@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3413 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3376 add domain name for virtual host match in envoy filters
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
Labels: size/M, release-notes-none

#3415 Run make gen
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/proxy_config.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/XS, release-notes-none

#3416 fix virtual service retry docs
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: size/XS, release-notes-none

#3419 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3417 AuthorizationPolicy serviceAccount: allow same namespace
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  tests/testdata/authz-valid.yaml
Labels: size/XS, release-notes-none

#3421 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3423 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3424 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#3414 Validation: remove CEL for PolicyTargetRef to allow vendor extensions
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  releasenotes/notes/3412.yaml
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  type/v1beta1/selector.pb.go
  type/v1beta1/selector.pb.html
  type/v1beta1/selector.proto
Labels: size/S

#3425 [release-1.25] Validation: remove CEL for PolicyTargetRef to allow vendor extensions
  extensions/v1alpha1/wasm.pb.go
  extensions/v1alpha1/wasm.pb.html
  extensions/v1alpha1/wasm.proto
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/envoy_filter.pb.html
  networking/v1alpha3/envoy_filter.proto
  releasenotes/notes/3412.yaml
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.pb.html
  security/v1beta1/authorization_policy.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.pb.html
  security/v1beta1/request_authentication.proto
  telemetry/v1alpha1/telemetry.pb.go
  telemetry/v1alpha1/telemetry.pb.html
  telemetry/v1alpha1/telemetry.proto
  type/v1beta1/selector.pb.go
  type/v1beta1/selector.pb.html
  type/v1beta1/selector.proto
Labels: size/S, release-notes-none

#3361 Add a pod-level opt-out for ambient DNS proxying, in preparation for enabling that by default globally
  annotation/annotations.gen.go
  annotation/annotations.yaml
  releasenotes/notes/3361.yaml
Labels: size/S
