Repository istio/api, pull requests merged in 2025-08, with the labels that each got.

#3548 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3552 Run make gen with latest build container
  analysis/v1alpha1/message.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  go.mod
  go.sum
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/proxy_config.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/M, release-notes-none

#3554 Automator: update common-files@release-1.26 in istio/api@release-1.26
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3556 [release-1.27] Clarify Service Entry addresses behavior limitations
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/service_entry.pb.html
  networking/v1alpha3/service_entry.proto
Labels: size/XS, release-notes-none

#3557 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
