Repository istio/api, pull requests merged in 2025-03, with the labels that each got.

#3453 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#3455 Remove non-zero requirement on connectionPool.tcp.IdleTimeout
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
Labels: size/XS, release-notes-none, cherrypick/release-1.23, cherrypick/release-1.24, cherrypick/release-1.25

#3462 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#3458 [release-1.25] Remove non-zero requirement on connectionPool.tcp.IdleTimeout
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
Labels: size/XS, release-notes-none

#3459 [release-1.24] Remove non-zero requirement on connectionPool.tcp.IdleTimeout (#3455)
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
Labels: size/XS, release-notes-none

#3460 [release-1.23] Remove non-zero requirement on connectionPool.tcp.IdleTimeout (#3455)
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.proto
Labels: release-notes-none

#3465 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3468 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3461 add retry backoff interval
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: size/XS, release-notes-none

#3469 add annotation for statsCompression
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/S, release-notes-none

#3472 Automator: update common-files@release-1.25 in istio/api@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3473 Automator: update common-files@release-1.23 in istio/api@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3475 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3477 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3478 update protos
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  go.mod
  go.sum
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/proxy_config.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/M, release-notes-none
