Repository istio/api, pull requests merged in 2025-02, with the labels that each got.

#3428 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3429 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3434 [release-1.25] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
Labels: size/XS, release-notes-none

#3436 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3439 Automator: update common-files@release-1.25 in istio/api@release-1.25
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3441 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3440 Run make gen
  analysis/v1alpha1/message.pb.go
  authentication/v1alpha1/policy.pb.go
  envoy/config/filter/http/alpn/v2alpha1/config.pb.go
  envoy/config/filter/http/authn/v2alpha1/config.pb.go
  envoy/config/filter/http/jwt_auth/v2alpha1/config.pb.go
  envoy/config/filter/network/metadata_exchange/metadata_exchange.pb.go
  envoy/config/filter/network/tcp_cluster_rewrite/v2alpha1/config.pb.go
  envoy/extensions/stackdriver/config/v1alpha1/config.pb.go
  envoy/extensions/stats/config.pb.go
  extensions/v1alpha1/wasm.pb.go
  mcp/v1alpha1/metadata.pb.go
  mcp/v1alpha1/resource.pb.go
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/proxy.pb.go
  meta/v1alpha1/status.pb.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/envoy_filter.pb.go
  networking/v1alpha3/gateway.pb.go
  networking/v1alpha3/service_entry.pb.go
  networking/v1alpha3/sidecar.pb.go
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/workload_entry.pb.go
  networking/v1alpha3/workload_group.pb.go
  networking/v1beta1/proxy_config.pb.go
  security/v1alpha1/ca.pb.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/request_authentication.pb.go
  telemetry/v1alpha1/telemetry.pb.go
  type/v1beta1/selector.pb.go
Labels: size/XS, release-notes-none

#3443 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3433 Clarify relationship btw MeshNetworks and ENABLE_HCM_INTERNAL_NET
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
  mesh/v1alpha1/network.pb.go
  mesh/v1alpha1/network.proto
  releasenotes/notes/mesh-network-internal-addr-config.yaml
Labels: size/M, cherrypick/release-1.25

#3432 add retry host predicate api
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1alpha3/virtual_service.pb.go
  networking/v1alpha3/virtual_service.pb.html
  networking/v1alpha3/virtual_service.proto
Labels: size/XS, release-notes-none

#3446 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3447 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#3426 envoy file provider support `omit_empty_values`
  mesh/v1alpha1/config.pb.go
  mesh/v1alpha1/config.proto
  mesh/v1alpha1/istio.mesh.v1alpha1.pb.html
Labels: size/XS, release-notes-none

#3448 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#3449 Automator: update common-files@master in istio/api@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
