Repository istio/api, pull requests merged in 2025-09, with the labels that each got.

#3564 Fix incorrect annotation in kubevirtInterfaces docs
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/XS, release-notes-none

#3562 stats: add bootstrap annotations for stats flush and eviction
  annotation/annotations.gen.go
  annotation/annotations.pb.html
  annotation/annotations.yaml
Labels: size/S, release-notes-none

#3523 add support for additional cookie attributes
  kubernetes/customresourcedefinitions.gen.yaml
  networking/v1/destination_rule_alias.gen.go
  networking/v1alpha3/destination_rule.pb.go
  networking/v1alpha3/destination_rule.pb.html
  networking/v1alpha3/destination_rule.proto
  networking/v1alpha3/destination_rule_deepcopy.gen.go
  networking/v1alpha3/destination_rule_json.gen.go
  networking/v1beta1/destination_rule_alias.gen.go
Labels: size/S, release-notes-none

#3567 Migrate storage version of security APIs to v1
  kubernetes/customresourcedefinitions.gen.yaml
  releasenotes/notes/storage-version-security.yaml
  security/v1/authorization_policy_alias.gen.go
  security/v1/peer_authentication_alias.gen.go
  security/v1/request_authentication_alias.gen.go
  security/v1beta1/authorization_policy.pb.go
  security/v1beta1/authorization_policy.proto
  security/v1beta1/peer_authentication.pb.go
  security/v1beta1/peer_authentication.proto
  security/v1beta1/request_authentication.pb.go
  security/v1beta1/request_authentication.proto
Labels: size/S

#3572 Automator: update common-files@master in istio/api@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none
